import {parseHTML} from 'linkedom';
import {fleetPictureMarkup} from '../src/supabase-fleet.js';
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const destinations={
 'san-diego-exotic-car-rental':{theme:'coast',city:'San Diego',eyebrow:'Exotic & luxury car rentals · San Diego',image:'/assets/locations/san-diego-coast.webp',alt:'Illustrative Pacific coastline with palms and sandstone cliffs',heading:'San Diego.<br /><em>Take the scenic route.</em>',caption:'Pacific views. Your kind of drive.',edit:'coastal',storyKicker:'From the coast to the city',intro:'Ocean air. Open roads. An arrival worth remembering.',note:'La Jolla · Del Mar · Coronado',fleetTitle:'Made for a coastal escape.',storyTitle:'A different view at every turn.',storyIntro:'Choose a convertible for a weekend by the water, a supercar for a special arrival, or a luxury SUV for the whole stay.',cta:'Your San Diego escape starts here.',cars:['porsche-911-carrera-cabriolet-rental','lamborghini-huracan-evo-spyder-rental','lamborghini-urus-performante-yellow-rental']},
 'los-angeles-exotic-car-rental':{theme:'la',city:'Los Angeles',eyebrow:'Exotic & luxury rentals · Los Angeles',image:'/assets/locations/los-angeles-sunset.webp',alt:'Los Angeles skyline at sunset',intro:'City lights. Coastal roads. A car that makes the arrival yours.',note:'Beverly Hills · West Hollywood · Malibu',fleetTitle:'For a city that never blends in.',storyTitle:'Make the city your own.',storyIntro:'From a dinner in Beverly Hills to a weekend on the coast, the details make the drive.',cta:'Your next LA arrival starts here.',cars:['mclaren-750s-rental','porsche-911-gt3-rs-rental','rolls-royce-cullinan-black-badge-rental']},
 'palm-springs-exotic-car-rental':{theme:'desert',city:'Palm Springs',eyebrow:'Exotic & luxury rentals · The desert',image:'/assets/locations/palm-springs-sunset.webp',alt:'Palm trees and desert mountains at sunset in the Coachella Valley',intro:'Open skies. Unhurried days. A little more room to enjoy the drive.',note:'Palm Springs · Palm Desert · Rancho Mirage',fleetTitle:'Find your desert escape.',storyTitle:'Settle into a different pace.',storyIntro:'Resort weekends, wedding arrivals, and time away. Plan the car around the stay.',cta:'Your desert weekend, beautifully arranged.',cars:['porsche-911-carrera-cabriolet-rental','bentley-continental-gtc-rental','lamborghini-huracan-evo-spyder-rental']}
};
export function refineDestinationPage(html,page,inventory,enhancements){
 const config=destinations[page.slug];if(!config)return html;
 const {document}=parseHTML(html);document.body.classList.add('destination-page','destination-'+config.theme);const css=document.createElement('link');css.href='/src/destination-pages.css';css.rel='stylesheet';document.head.append(css);
 document.querySelector('meta[property="og:image"]')?.setAttribute('content','https://www.prestigeluxor.com'+config.image);
 const selected=config.cars.map(slug=>inventory.find(c=>c.slug===slug)).filter(Boolean);
 const cards=selected.map(car=>{const photo=[...(car.car_photos||[])].sort((a,b)=>Number(a.position)-Number(b.position)).find(p=>p.url)?.url||car.image_url;return `<article class="destination-car"><a class="destination-car-image" href="/cars/${car.slug}" aria-label="View ${escape(car.name)}">${fleetPictureMarkup(photo,{alt:car.name,width:1200,height:900,loading:'lazy',updatedAt:car.updated_at})}</a><div class="destination-car-copy"><p>${escape(car.make)}</p><h3>${escape(car.model||car.name)}</h3><p class="destination-rate">From <strong>$${Number(car.price).toLocaleString('en-US')}</strong> / day</p></div><a class="destination-car-link" href="/cars/${car.slug}">Photos &amp; details <span aria-hidden="true">↗</span></a><a class="destination-car-request" href="#location-quote" data-location-vehicle="${escape(car.name)}">Request this car <span aria-hidden="true">→</span></a></article>`;}).join('');
 const main=document.querySelector('main');main.className='destination-main';
 main.innerHTML=`<section class="destination-hero" aria-labelledby="destination-title"><div class="destination-hero-copy"><p class="destination-kicker">${config.eyebrow}</p><h1 id="destination-title">${config.heading||`Exotic car rental.<br /><em>${config.city}.</em>`}</h1><p class="destination-intro">${config.intro}</p><p class="destination-description">${escape(page.lead)}</p><div class="destination-actions"><a class="destination-primary" href="#destination-fleet">Explore the cars <span aria-hidden="true">↗</span></a><a class="destination-secondary" href="#location-quote">Plan your delivery <span aria-hidden="true">→</span></a></div><p class="destination-note">${config.note}</p></div><figure class="destination-scene"><img src="${config.image}" alt="${config.alt}" width="900" height="1100" fetchpriority="high" decoding="async" /><figcaption>${config.caption||(config.theme==='la'?'The city, in its best light.':'Stay a little longer.')}</figcaption></figure></section>
 <section class="destination-fleet" id="destination-fleet" aria-labelledby="destination-fleet-title"><header class="destination-section-heading"><div><p class="destination-kicker">The ${config.edit||(config.theme==='la'?'Los Angeles':'desert')} edit</p><h2 id="destination-fleet-title">${config.fleetTitle}</h2></div><a href="/fleet">View all cars <span aria-hidden="true">↗</span></a></header><div class="destination-cars">${cards||'<p>Contact the concierge for current vehicle availability.</p>'}</div><p class="destination-fleet-note">Starting daily rates. Your exact vehicle, dates, and delivery are confirmed with your quote.</p></section>
 <section class="destination-story"><div class="destination-story-intro"><p class="destination-kicker">${config.storyKicker||(config.theme==='la'?'Your plans. Your pace.':'A change of scenery')}</p><h2>${config.storyTitle}</h2><p>${config.storyIntro}</p><a href="#location-quote">Arrange your arrival <span aria-hidden="true">↗</span></a></div><div class="destination-local-details">${page.content}</div></section>
 ${enhancements}
 <section class="destination-closing"><p class="destination-kicker">Prestige Luxor · ${config.city}</p><h2>${config.cta}</h2><a href="#location-quote" class="destination-primary">Request your dates <span aria-hidden="true">↗</span></a></section>`;
 return '<!doctype html>\n'+document.documentElement.outerHTML;
}
