// Rental guides use the same published inventory snapshot as vehicle pages.
export function rentalGuides(inventory, { escapeHtml: e, formatUsd: usd }) {
  const lambos = inventory.filter(car => /lamborghini/i.test(car.make) && Number(car.price) > 0).sort((a,b) => a.price - b.price);
  const link = car => `<a href="/cars/${e(car.slug)}">${e(car.name)}</a>`;
  const range = cars => cars.length ? `${usd(Math.min(...cars.map(c => c.price)))}–${usd(Math.max(...cars.map(c => c.price)))}` : 'Quote on request';
  const huracan = lambos.find(c => c.slug === '2022-lamborghini-huracan') || lambos.find(c => /hurac[aá]n/i.test(c.name));
  const urus = lambos.find(c => c.slug === 'lamborghini-urus-black') || lambos.find(c => /urus/i.test(c.name));
  const note = '<p class="guide-note">By Prestige Luxor · Published October 8, 2026. Rates reflect our published inventory and may change. They are starting daily rates, not a confirmed total or a promise of availability. Check the vehicle page and request a quote for your dates.</p>';
  const cta = '<section><h2>Get a quote for your trip</h2><p>Send your dates, preferred vehicle, passenger count and delivery city. We will confirm availability and rental terms before you reserve.</p><p><a class="primary-button" href="/#quote">Request your quote</a> <a href="/rental-policies">Read rental policies</a></p></section>';
  const pages = [{
    path: 'guides/lamborghini-rental-cost-southern-california',
    title: 'Lamborghini Rental Cost in Southern California | Prestige Luxor',
    heading: 'How much does a Lamborghini rental cost in Southern California?',
    description: 'Compare Prestige Luxor Lamborghini starting daily rates, included mileage and the details that determine your final Southern California rental quote.',
    lead: `Prestige Luxor’s published Lamborghini rentals currently start at ${range(lambos)} per day. Your model, dates, rental length and delivery address determine the confirmed quote.`,
    content: `${note}<section><h2>Compare published Lamborghini rates</h2><p>These are rates from our own fleet, not a market-wide average. Open a model to see its photos and request dates.</p><div class="guide-table-wrap" tabindex="0" role="region" aria-label="Lamborghini daily rates"><table class="guide-table"><caption>Prestige Luxor Lamborghini starting daily rates</caption><thead><tr><th scope="col">Vehicle</th><th scope="col">Starting rate</th><th scope="col">Listed mileage</th></tr></thead><tbody>${lambos.map(c => `<tr><th scope="row">${link(c)}</th><td>${usd(c.price)}/day</td><td>${e(c.mileage || 'Confirm with quote')}</td></tr>`).join('')}</tbody></table></div></section>
    <section><h2>What determines the final rental total?</h2><ul><li><strong>Vehicle and dates:</strong> request the specific car and rental period, including pickup and return times.</li><li><strong>Delivery:</strong> share the city and address so we can confirm timing, access and any delivery charges.</li><li><strong>Mileage:</strong> compare your planned route with the agreed allowance and ask for the excess-mile rate before booking.</li><li><strong>Additional charges:</strong> ask for an itemized quote showing applicable taxes, fees and any approved extras.</li><li><strong>Security deposit:</strong> confirm the amount and release conditions separately from the rental price.</li></ul></section>
    ${huracan ? `<section><h2>A three-day rental example</h2><p>At the published ${usd(huracan.price)} daily starting rate for the ${link(huracan)}, three days of base rental would be ${usd(huracan.price * 3)}. This is an illustration only; it excludes any delivery charges, applicable taxes, fees, extras and security deposit. Your confirmed daily rate and terms may differ for your dates.</p></section>` : ''}
    <section><h2>Should you choose a Huracán or an Urus?</h2><p>Start with passenger needs and the trip itself. A two-seat sports car suits a trip for two; an SUV offers a different seating and luggage layout. <a href="/guides/lamborghini-huracan-vs-urus-rental">Compare our Huracán and Urus rental examples</a> before requesting a quote.</p></section>${cta}`
  }, {
    path: 'guides/lamborghini-huracan-vs-urus-rental',
    title: 'Lamborghini Huracán vs Urus Rental | Prestige Luxor',
    heading: 'Huracán or Urus: which Lamborghini fits your rental?',
    description: 'Compare actual Prestige Luxor Huracán and Urus rental examples by daily rate, seating, mileage and trip needs across Southern California.',
    lead: 'Choose the Huracán for a sports-car trip for two. Consider the Urus when your plans include more passengers or luggage. Compare the specific cars and confirm the details for your dates.',
    content: `${note}<section><h2>Two actual rental options</h2><p>These examples compare specific listed vehicles. Other model years, colors and versions may have different rates.</p><div class="guide-table-wrap" tabindex="0" role="region" aria-label="Huracán and Urus comparison"><table class="guide-table"><caption>Published rental details</caption><thead><tr><th scope="col">Detail</th><th scope="col">Huracán example</th><th scope="col">Urus example</th></tr></thead><tbody><tr><th scope="row">Vehicle</th><td>${huracan ? link(huracan) : 'Ask for current availability'}</td><td>${urus ? link(urus) : 'Ask for current availability'}</td></tr><tr><th scope="row">Starting daily rate</th><td>${huracan ? usd(huracan.price) : 'Quote on request'}</td><td>${urus ? usd(urus.price) : 'Quote on request'}</td></tr><tr><th scope="row">Listed seats</th><td>${huracan ? e(huracan.seats) : 'Confirm with quote'}</td><td>${urus ? e(urus.seats) : 'Confirm with quote'}</td></tr><tr><th scope="row">Listed mileage</th><td>${huracan ? e(huracan.mileage) : 'Confirm with quote'}</td><td>${urus ? e(urus.mileage) : 'Confirm with quote'}</td></tr></tbody></table></div></section>
    <section><h2>When the Huracán makes sense</h2><p>Consider the Huracán for an occasion or a drive with one passenger. Plan around the two-seat layout and check luggage fit before booking an airport delivery. If roof style matters, choose the exact vehicle shown on its listing rather than assuming every Huracán is a convertible.</p></section>
    <section><h2>When to consider the Urus</h2><p>Consider the Urus for a hotel stay, a group trip or a schedule with more passengers. Confirm the exact seating configuration, luggage dimensions and any child-seat requirements with the booking desk. A listed seat count alone does not establish that your group and all bags will fit comfortably.</p></section>
    <section><h2>Compare more than the daily rate</h2><p>Ask for quotes covering the same dates, delivery address and planned mileage. Confirm the deposit, driver eligibility, insurance requirements and total charges for each option. Our <a href="/guides/lamborghini-rental-cost-southern-california">Lamborghini pricing guide</a> explains what to include in that comparison.</p></section>
    <section><h2>Tell us how you will use the car</h2><ul><li>How many people will travel, including the driver?</li><li>How many bags are you bringing, and what are their dimensions?</li><li>Is the trip mainly a special occasion, hotel stay or longer itinerary?</li><li>Where and when should delivery and return happen?</li></ul><p><a href="/lamborghini">Browse all Lamborghini rentals</a> or review our <a href="/guides/exotic-car-delivery-hotels-airports">hotel and airport delivery guide</a>.</p></section>${cta}`
  }, {
    path: 'guides/exotic-car-delivery-hotels-airports',
    title: 'Exotic Car Delivery to Hotels & Airports in Southern California | Prestige Luxor',
    heading: 'Planning exotic car delivery to your hotel or airport.',
    description: 'Plan a Prestige Luxor rental delivery across Southern California: hotel access, airport meeting points, arrival timing, luggage and return arrangements.',
    lead: 'Prestige Luxor offers delivery across Southern California. The vehicle, address, access and timing must be confirmed with your quote. Airport delivery does not automatically mean a terminal-curbside handoff.',
    content: `<p class="guide-note">By Prestige Luxor · Published October 8, 2026.</p><section><h2>For hotel delivery</h2><p>Provide the hotel name, address, arrival time and a reachable contact number. Ask the hotel whether a vehicle handoff is permitted at its entrance or valet area. We will agree on the meeting point and any delivery charges before the rental is confirmed.</p><p>Tell us if the property has restricted access, steep ramps or parking constraints. Confirm parking and valet arrangements directly with the property; those services are not implied by the rental.</p></section>
    <section><h2>For airport arrivals</h2><p>Share your airport, flight arrival time, passenger count and luggage details. The booking desk will confirm a permitted meeting point and timing. Do not assume curbside pickup or access to a rental-car facility unless those arrangements have been explicitly confirmed.</p><ul><li><a href="/locations/lax-exotic-car-delivery">LAX exotic car delivery</a>: confirm your terminal, arrival timing and meeting location.</li><li><a href="/locations/sna-exotic-car-delivery">John Wayne Airport delivery</a>: confirm access and the handoff plan before arrival.</li><li><a href="/locations/san-diego-exotic-car-rental">San Diego rentals</a> and <a href="/locations/palm-springs-exotic-car-rental">Palm Springs rentals</a>: request delivery for the exact address or airport you need.</li></ul><p>If your flight changes, contact the booking desk so delivery timing can be reviewed. Any revised arrangement remains subject to confirmation.</p></section>
    <section><h2>Choose the car around passengers and bags</h2><p>A two-seat exotic and a luxury SUV serve different trips. Send the number and dimensions of your bags before reserving, especially for airport delivery. <a href="/guides/lamborghini-huracan-vs-urus-rental">Compare the Huracán and Urus</a> for two different rental layouts.</p></section>
    <section><h2>Agree on the return before you arrive</h2><p>Confirm the return location, time, mileage allowance and fuel requirements in your rental agreement. If pickup and return addresses differ, request that arrangement with your initial quote. Allow time for the vehicle handoff when planning your departure.</p></section>
    <section><h2>Your delivery request checklist</h2><ol><li>Choose a vehicle and share rental dates with pickup and return times.</li><li>Provide delivery and return addresses, or airport and flight details.</li><li>Confirm passenger count, luggage and property access.</li><li>Review the itemized quote, mileage, deposit and driver requirements.</li><li>Complete the required approval and agreement before the scheduled handoff.</li></ol><p>For full requirements, see our <a href="/rental-policies">rental policies</a>. Delivery availability is confirmed individually; location pages do not represent walk-in offices.</p></section>${cta}`
  }];
  for (const page of pages) page.content += `<section><h2>More rental guides</h2><ul>${pages.filter(other => other !== page).map(other => `<li><a href="/${other.path}">${e(other.heading)}</a></li>`).join('')}</ul><p><a href="/guides">All rental guides</a></p></section>`;
  return pages;
}
