import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "./supabase-config.js?v=fleet-sync-20260714";
import { clearDraft, draftData, restoreForm, scheduleDraft, serializeForm, writeDraft } from "./form-drafts.js";

const supabase=window.prestigeLuxorSupabase||createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=(selector)=>document.querySelector(selector);
const form=$("[data-agreement-form]"),list=$("[data-agreement-list]"),empty=$("[data-agreement-empty]"),statusEl=$("[data-agreement-status]"),search=$("[data-agreement-search]"),kpis=$("[data-agreement-kpis]");
const sourceType=$("[data-agreement-source-type]"),sourceSelect=$("[data-agreement-source]"),title=$("[data-agreement-title]"),subtitle=$("[data-agreement-subtitle]"),badge=$("[data-agreement-badge]");
const linkCard=$("[data-agreement-link-card]"),linkStatus=$("[data-agreement-link-status]"),audit=$("[data-agreement-audit]"),auditList=$("[data-agreement-audit-list]");
const saveButton=$("[data-save-agreement]"),sendButton=$("[data-resend-agreement]"),downloadButton=$("[data-download-agreement]"),deleteButton=$("[data-delete-agreement]");
const templateForm=$("[data-agreement-template-form]"),templateTerms=$("[data-agreement-template-terms]"),templateStatus=$("[data-agreement-template-status]");
const DRAFT_KEY="prestige-luxor:draft:new-agreement:v2";
let agreements=[],invoices=[],quotes=[],current=null,events=[],publicUrl="",role="staff",template=null,loaded=false,settingsLoaded=false;

const escapeHtml=(value)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=(value)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(value||0));
const dateTime=(value)=>value?new Date(value).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}):"To be confirmed";
const localInput=(value)=>{if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value).length===10?`${value}T10:00`:"";date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};
const setStatus=(message="",tone="")=>{statusEl.textContent=message;statusEl.dataset.tone=tone;};

async function token(){const{data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Sign in again to use agreements.");return data.session.access_token;}
async function api(path="agreements",options={}){const response=await fetch(`/api/${path}`,{...options,headers:{Authorization:`Bearer ${await token()}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});if(path.startsWith("agreement-pdf")&&response.ok)return response;const data=await response.json().catch(()=>({}));if(!response.ok){if([404,405,501].includes(response.status)&&["localhost","127.0.0.1","0.0.0.0"].includes(location.hostname))throw new Error("Agreement saving needs the full application server. Restart the preview with Vercel Dev, then try again.");const message=data.error||"Agreement request failed.";if(/agreement_templates|important_terms|access_token|signed_pdf/i.test(message)&&/schema|column|table|cache|not found/i.test(message))throw new Error("The new agreement database update is not installed yet. Run supabase/rental-agreements.sql in the Supabase SQL Editor, then refresh.");throw new Error(message);}return data;}

function sourceRows(){if(sourceType.value==="invoice")return invoices.map(item=>({id:item.id,label:`${item.invoice_number} · ${item.customer_name} · ${item.vehicle_name}`,item}));if(sourceType.value==="quote")return quotes.map(item=>({id:item.id,label:`${item.quote_number||"Quote"} · ${[item.customer_first_name,item.customer_last_name].filter(Boolean).join(" ")} · ${item.vehicle_name}`,item}));return[];}
function populateSources(selected=""){const rows=sourceRows();sourceSelect.disabled=sourceType.value==="manual";sourceSelect.innerHTML=`<option value="">${rows.length?"Select a rental record":"No records available"}</option>${rows.map(row=>`<option value="${escapeHtml(row.id)}" ${String(row.id)===String(selected)?"selected":""}>${escapeHtml(row.label)}</option>`).join("")}`;}
function latestDriver(customer={}){const email=String(customer.customer_email||customer.email||"").toLowerCase(),phone=String(customer.customer_phone||customer.phone||"").replace(/\D/g,"");return agreements.find(item=>item.license_number&&((email&&String(item.customer_email||"").toLowerCase()===email)||(phone&&String(item.customer_phone||"").replace(/\D/g,"")===phone)));}
function sourceValues(type,item){if(type==="invoice"){const prior=latestDriver(item)||{};return{source_type:"invoice",source_id:item.id,customer_name:item.customer_name||"",customer_phone:item.customer_phone||"",customer_email:item.customer_email||"",driver_name:item.customer_name||"",license_number:prior.license_number||"",license_state:prior.license_state||"",license_expiration:prior.license_expiration||"",vehicle_name:item.vehicle_name||"",rental_start:item.rental_start||"",rental_end:item.rental_end||"",rental_start_at:localInput(item.rental_start),rental_end_at:localInput(item.rental_end),rental_days:item.rental_days||1,daily_rate:item.daily_rate||0,quote_total:item.subtotal||Math.max(Number(item.total||0)-(item.deposit_method==="charge"?Number(item.refundable_deposit||0):0),0),refundable_deposit:item.refundable_deposit||0,mileage_allowance:item.mileage_allowance||"100 miles/day",overage_rate:Number(String(item.overage_rate||"").replace(/[^0-9.]/g,""))||0,payment_status:item.status==="paid"?"paid":item.status==="partially_paid"?"partial":"unpaid",amount_paid:item.amount_paid||0,payment_method:item.payment_method||"stripe",payment_reference:item.payment_reference||"",deposit_status:item.deposit_method==="authorization_hold"?"held":Number(item.refundable_deposit)?"charged":"not_required"};}const prior=latestDriver({email:item.customer_email,phone:item.customer_phone})||{};return{source_type:"quote",source_id:item.id,quote_id:item.id,vehicle_id:item.vehicle_id||null,customer_name:[item.customer_first_name,item.customer_last_name].filter(Boolean).join(" "),customer_phone:item.customer_phone||"",customer_email:item.customer_email||"",driver_name:[item.customer_first_name,item.customer_last_name].filter(Boolean).join(" "),license_number:prior.license_number||"",license_state:prior.license_state||"",license_expiration:prior.license_expiration||"",vehicle_name:item.vehicle_name||"",rental_start_at:localInput(item.start_at),rental_end_at:localInput(item.end_at),rental_start:String(item.start_at||"").slice(0,10),rental_end:String(item.end_at||"").slice(0,10),rental_days:item.duration_type==="days"?item.duration_value:1,daily_rate:item.rate_amount||0,quote_total:item.rental_total||0,refundable_deposit:item.security_deposit||0,mileage_allowance:"100 miles/day",payment_status:Number(item.deposit_paid_amount)>=Number(item.rental_total)?"paid":Number(item.deposit_paid_amount)>0?"partial":"unpaid",amount_paid:item.deposit_paid_amount||0,deposit_status:Number(item.security_deposit)?"pending":"not_required"};}
function applyValues(values){Object.entries(values||{}).forEach(([name,value])=>{if(!form.elements[name])return;form.elements[name].value=["rental_start_at","rental_end_at"].includes(name)&&value?localInput(value):value??"";});renderSummary();}
function applySource(){const row=sourceRows().find(item=>String(item.id)===sourceSelect.value);if(row)applyValues(sourceValues(sourceType.value,row.item));}

function payload(){const data=Object.fromEntries(new FormData(form));const start=data.rental_start_at?new Date(data.rental_start_at):null,end=data.rental_end_at?new Date(data.rental_end_at):null;const days=start&&end&&end>start?Math.max(Math.ceil((end-start)/86400000),1):1;return{...data,id:current?.id||undefined,rental_start_at:start?.toISOString?.()||null,rental_end_at:end?.toISOString?.()||null,rental_start:data.rental_start_at?.slice(0,10)||null,rental_end:data.rental_end_at?.slice(0,10)||null,rental_days:days,daily_rate:Number(data.quote_total||0)/days,quote_total:Number(data.quote_total||0),refundable_deposit:Number(data.refundable_deposit||0),overage_rate:Number(data.overage_rate||0),driver_name:data.customer_name,terms:template?.body,important_terms:template?.important_terms,template_version:template?.version};}
function renderSummary(){if(!form||form.hidden)return;const p=payload();$("[data-agreement-summary]").innerHTML=`<article><span>Renter</span><strong>${escapeHtml(p.customer_name||"Not selected")}</strong></article><article><span>Vehicle</span><strong>${escapeHtml(p.vehicle_name||"Not selected")}</strong></article><article><span>Rental dates</span><strong>${escapeHtml(dateTime(p.rental_start_at))}<small>to ${escapeHtml(dateTime(p.rental_end_at))}</small></strong></article><article><span>Rental amount</span><strong>${money(p.quote_total)}</strong></article><article><span>Security deposit</span><strong>${money(p.refundable_deposit)}</strong></article>`;}
function renderList(){const query=String(search?.value||"").toLowerCase();const rows=agreements.filter(item=>[item.agreement_number,item.customer_name,item.vehicle_name].some(value=>String(value||"").toLowerCase().includes(query)));list.innerHTML=rows.length?rows.map(item=>`<button class="invoice-list-item ${current?.id===item.id?"active":""}" type="button" data-select-agreement="${item.id}"><span><strong>${escapeHtml(item.agreement_number)}</strong><small>${escapeHtml(item.status.replaceAll("_"," "))}</small></span><b>${escapeHtml(item.customer_name)}</b><span><small>${escapeHtml(item.vehicle_name)}</small><strong>${money(item.quote_total||item.rental_total)}</strong></span></button>`).join(""):`<p class="admin-empty">No matching agreements.</p>`;kpis.innerHTML=`<article><span>Total</span><strong>${agreements.length}</strong></article><article><span>Needs signature</span><strong>${agreements.filter(item=>item.status==="draft").length}</strong></article><article><span>Signed</span><strong>${agreements.filter(item=>item.status==="signed").length}</strong></article><article><span>Signed this month</span><strong>${agreements.filter(item=>item.signed_at&&String(item.signed_at).slice(0,7)===new Date().toISOString().slice(0,7)).length}</strong></article>`;}
function renderAudit(){audit.hidden=!current;const rows=[...events];if(current?.created_at&&!rows.some(event=>event.event_type==="created"))rows.push({event_type:"created",detail:"Agreement created.",created_at:current.created_at});auditList.innerHTML=rows.length?rows.map(event=>`<article><i></i><div><strong>${escapeHtml(event.event_type.replaceAll("_"," "))}</strong><span>${escapeHtml(event.detail||"")}</span><time>${escapeHtml(dateTime(event.created_at))}</time></div></article>`).join(""):`<p>No audit events yet.</p>`;}
function setLocked(locked){form.querySelectorAll("[data-agreement-editable] input,[data-agreement-editable] select").forEach(field=>field.disabled=locked);saveButton.hidden=locked;deleteButton.hidden=!current||role!=="owner";deleteButton.textContent=current?.status==="draft"?"Delete draft":"Delete agreement";sendButton.hidden=!current;downloadButton.hidden=!current;linkCard.hidden=!current;subtitle.textContent=locked?"Signed agreements are locked. The saved PDF is the record copy.":"Review the rental summary before sending it to the renter.";}
async function openAgreement(item=null,options={}){current=item?.id?item:null;events=[];publicUrl="";empty.hidden=true;form.hidden=false;form.reset();const defaults=item||options.defaults||{source_type:"invoice",mileage_allowance:"100 miles/day",quote_total:0,refundable_deposit:0};applyValues(defaults);sourceType.value=defaults.source_type||"invoice";populateSources(defaults.source_id||"");if(!item&&!options.defaults){const saved=draftData(DRAFT_KEY)?.fields;restoreForm(form,saved);sourceType.value=form.elements.source_type.value||"invoice";populateSources(form.elements.source_id.value||"");if(saved)setStatus("Your unsaved agreement draft was restored.","success");}title.textContent=item?.agreement_number||"New agreement";badge.textContent=(item?.status||"draft").replaceAll("_"," ");badge.className=`invoice-status-badge ${item?.status||"draft"}`;setLocked(Boolean(item&&item.status!=="draft"));renderSummary();renderList();renderAudit();if(item)await loadDetail(item.id);form.scrollIntoView({behavior:"smooth",block:"start"});}
async function loadDetail(id){try{const data=await api(`agreements?id=${encodeURIComponent(id)}`);current=data.agreement;events=data.events||[];publicUrl=data.public_url||"";linkStatus.textContent=current.status==="signed"?"Signed PDF saved":current.opened_at?"Opened by renter":"Ready to send";setLocked(current.status!=="draft");renderAudit();renderList();}catch(error){setStatus(error.message,"error");}}

async function load(force=false){if(loaded&&!force){renderList();return;}setStatus("Loading agreements…");try{const [agreementData,invoiceData,quoteData,templateData]=await Promise.all([api(),supabase.from("invoices").select("*").neq("status","void").order("created_at",{ascending:false}).limit(500),supabase.from("quotes").select("*").order("created_at",{ascending:false}).limit(500),api("agreement-settings")]);agreements=agreementData.agreements||[];role=agreementData.role||"staff";invoices=invoiceData.data||[];quotes=quoteData.data||[];template=templateData.template;loaded=true;renderList();setStatus("");if(!current&&draftData(DRAFT_KEY))openAgreement();}catch(error){setStatus(error.message,"error");if(!current&&draftData(DRAFT_KEY))openAgreement();}}
async function save(event){event?.preventDefault();if(!form.reportValidity())return;try{saveButton.disabled=true;setStatus("Saving agreement and creating the private signing link…");const body=payload();const data=await api("agreements",{method:current?"PATCH":"POST",body:JSON.stringify(body)});clearDraft(DRAFT_KEY);current=data.agreement;if(!agreements.some(item=>item.id===current.id))agreements.unshift(current);await openAgreement(current);publicUrl=data.public_url||publicUrl;setStatus("Agreement saved. The private signing link is ready.","success");}catch(error){setStatus(error.message,"error");}finally{saveButton.disabled=false;}}
async function send(){if(!current)return;try{sendButton.disabled=true;setStatus("Sending the agreement…");const data=await api("agreements",{method:"POST",body:JSON.stringify({action:"send",id:current.id})});publicUrl=data.public_url||publicUrl;await loadDetail(current.id);setStatus(data.delivery?.delivered?`Agreement emailed to ${current.customer_email}.`:data.delivery?.reason||"Signing link ready to copy.",data.delivery?.delivered?"success":"");}catch(error){setStatus(error.message,"error");}finally{sendButton.disabled=false;}}
async function remove(){if(!current)return;const locked=current.status!=="draft";const warning=locked?`Delete ${current.agreement_number}? This permanently removes the signed PDF and audit trail. This cannot be undone.`:`Delete draft ${current.agreement_number}? This cannot be undone.`;if(!confirm(warning))return;let confirmation="";if(locked){confirmation=prompt("Type DELETE to permanently remove this agreement:")||"";if(confirmation!=="DELETE"){setStatus("Agreement deletion cancelled.");return;}}try{deleteButton.disabled=true;await api(`agreements?id=${encodeURIComponent(current.id)}${locked?"&confirm=DELETE":""}`,{method:"DELETE"});const label=current.agreement_number;current=null;form.hidden=true;empty.hidden=false;await load(true);setStatus(`${label} deleted.`,"success");}catch(error){setStatus(error.message,"error");}finally{deleteButton.disabled=false;}}
async function download(){if(!current)return;try{const response=await api(`agreement-pdf?id=${encodeURIComponent(current.id)}`),blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${current.agreement_number}.pdf`;link.click();URL.revokeObjectURL(url);}catch(error){setStatus(error.message,"error");}}

function renderTemplateTerms(){templateTerms.innerHTML=(template?.important_terms||[]).map((term,index)=>`<article data-template-term data-key="${escapeHtml(term.key)}"><span>${String(index+1).padStart(2,"0")}</span><label>Term title<input name="term_title" value="${escapeHtml(term.title)}" required /></label><label>Short acknowledgment<textarea name="term_body" rows="3" required>${escapeHtml(term.body)}</textarea></label></article>`).join("");}
async function loadSettings(){if(settingsLoaded)return;try{templateStatus.textContent="Loading agreement template…";const data=await api("agreement-settings");template=data.template;templateForm.elements.title.value=template.title||"";templateForm.elements.body.value=template.body||"";renderTemplateTerms();settingsLoaded=true;templateStatus.textContent=`Template version ${template.version||1}`;}catch(error){templateStatus.textContent=error.message;templateStatus.dataset.tone="error";}}
async function saveSettings(event){event.preventDefault();if(!templateForm.reportValidity())return;const terms=[...templateTerms.querySelectorAll("[data-template-term]")].map(row=>({key:row.dataset.key,title:row.querySelector('[name="term_title"]').value,body:row.querySelector('[name="term_body"]').value}));try{const button=templateForm.querySelector('button[type="submit"]');button.disabled=true;templateStatus.textContent="Saving a new template version…";const data=await api("agreement-settings",{method:"PUT",body:JSON.stringify({title:templateForm.elements.title.value,body:templateForm.elements.body.value,important_terms:terms})});template=data.template;templateStatus.textContent=`Template version ${template.version} saved. Existing agreements were not changed.`;templateStatus.dataset.tone="success";button.disabled=false;}catch(error){templateStatus.textContent=error.message;templateStatus.dataset.tone="error";templateForm.querySelector('button[type="submit"]').disabled=false;}}

form.addEventListener("submit",save);form.addEventListener("input",()=>{renderSummary();if(!current)scheduleDraft(DRAFT_KEY,()=>({fields:serializeForm(form)}));});form.addEventListener("change",()=>{renderSummary();if(!current)scheduleDraft(DRAFT_KEY,()=>({fields:serializeForm(form)}));});
sourceType.addEventListener("change",()=>populateSources());sourceSelect.addEventListener("change",applySource);search.addEventListener("input",renderList);
list.addEventListener("click",event=>{const button=event.target.closest("[data-select-agreement]");if(button)openAgreement(agreements.find(item=>item.id===button.dataset.selectAgreement));});
$("[data-new-agreement]").addEventListener("click",()=>openAgreement());$("[data-crm-section=agreements]").addEventListener("click",()=>load());$("[data-crm-section=settings]").addEventListener("click",loadSettings);
sendButton.addEventListener("click",send);downloadButton.addEventListener("click",download);deleteButton.addEventListener("click",remove);
$("[data-copy-agreement-link]").addEventListener("click",async()=>{if(!publicUrl)await loadDetail(current.id);await navigator.clipboard.writeText(publicUrl);setStatus("Private signing link copied.","success");});
$("[data-open-agreement-link]").addEventListener("click",async()=>{if(!publicUrl)await loadDetail(current.id);window.open(publicUrl,"_blank","noopener");});
templateForm.addEventListener("submit",saveSettings);
window.addEventListener("prestige:start-agreement",async event=>{try{const invoice=event.detail?.invoice;if(!invoice?.id)throw new Error("Save the invoice before continuing.");await load(true);const existing=agreements.find(item=>item.source_type==="invoice"&&String(item.source_id)===String(invoice.id));if(existing){await openAgreement(existing);setStatus(`${existing.agreement_number} is already connected to this invoice.`,"success");return;}clearDraft(DRAFT_KEY);await openAgreement(null,{defaults:sourceValues("invoice",invoice)});setStatus(`Invoice ${invoice.invoice_number} carried forward. Review the summary, then create the signing link.`,"success");}catch(error){setStatus(error.message,"error");}});
window.addEventListener("prestige:open-agreement",async event=>{await load(true);const agreement=agreements.find(item=>String(item.id)===String(event.detail?.id));if(agreement)openAgreement(agreement);});
window.addEventListener("pagehide",()=>{if(!current&&!form.hidden)writeDraft(DRAFT_KEY,{fields:serializeForm(form)});});
supabase.auth.onAuthStateChange((event,session)=>{if(!session){loaded=false;agreements=[];}else if($("[data-section-panel=agreements]")?.classList.contains("active"))load();});
