import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "./supabase-config.js?v=fleet-sync-20260714";

const DEFAULT_TERMS = "The renter confirms the vehicle, rental dates, rates, mileage allowance, and refundable security deposit shown above. Only approved drivers may operate the vehicle. The vehicle must be returned on time, with the agreed fuel level and in the same condition, ordinary wear excepted. The renter authorizes Prestige Luxor to document pickup and return condition and to apply properly documented mileage, fuel, toll, late-return, damage, cleaning, or other agreed charges against the refundable deposit. This operational template must be reviewed and customized by qualified legal counsel before customer use.";
const supabase = window.prestigeLuxorSupabase || createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $ = (selector) => document.querySelector(selector);
const form = $("[data-agreement-form]"), list = $("[data-agreement-list]"), empty = $("[data-agreement-empty]");
const statusEl = $("[data-agreement-status]"), search = $("[data-agreement-search]"), kpis = $("[data-agreement-kpis]");
const title = $("[data-agreement-title]"), badge = $("[data-agreement-badge]"), canvas = $("[data-signature-pad]");
const sourceType = $("[data-agreement-source-type]"), sourceSelect = $("[data-agreement-source]");
let agreements=[], quotes=[], invoices=[], current=null, role="staff", loaded=false, drawing=false, hasInk=false;

const escapeHtml=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const money=(v)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const setStatus=(message="",type="")=>{statusEl.textContent=message;statusEl.className=`admin-status ${type}`.trim();};
async function token(){const {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Sign in again to use agreements.");return data.session.access_token;}
async function api(path="agreements",options={}){const response=await fetch(`/api/${path}`,{...options,headers:{Authorization:`Bearer ${await token()}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});if(path.startsWith("agreement-pdf")&&response.ok)return response;const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Agreement request failed.");return data;}

function calculateDays(){const start=form.elements.rental_start.value,end=form.elements.rental_end.value,help=$("[data-agreement-days-help]");form.elements.rental_end.min=start;if(!start||!end){help.textContent="Calculated from the dates.";return;}const delta=Date.parse(`${end}T00:00:00Z`)-Date.parse(`${start}T00:00:00Z`);if(delta<0){form.elements.rental_end.setCustomValidity("End date must be after start date.");help.textContent="Choose an end date on or after the start.";return;}form.elements.rental_end.setCustomValidity("");const days=Math.max(1,Math.ceil(delta/86400000));form.elements.rental_days.value=days;renderMoney();}
function renderMoney(){const days=Math.max(Number(form.elements.rental_days.value)||1,1),rate=Number(form.elements.daily_rate.value)||0,deposit=Number(form.elements.refundable_deposit.value)||0;$("[data-agreement-money]").innerHTML=`<span>Rental total <strong>${money(days*rate)}</strong></span><span>Refundable deposit <strong>${money(deposit)}</strong></span>`;}
function payload(){const data=new FormData(form),out={};for(const [key,value] of data.entries()){if(value instanceof File)continue;out[key]=value;}const numbers=["rental_days","daily_rate","overage_rate","refundable_deposit","amount_paid","pickup_mileage","return_mileage","mileage_charge","fuel_charge","tolls_charge","damage_charge","other_charge","deposit_deduction"];for(const name of numbers)out[name]=out[name]===""?null:Number(out[name]||0);out.id=current?.id;out.pickup_photo_paths=current?.pickup_photo_paths||[];out.return_photo_paths=current?.return_photo_paths||[];out.license_file_path=current?.license_file_path||null;out.insurance_file_path=current?.insurance_file_path||null;return out;}
function sourceRecords(){if(sourceType.value==="invoice")return invoices.map(item=>({id:item.id,label:`${item.invoice_number} · ${item.customer_name} · ${item.vehicle_name}`}));if(sourceType.value==="quote")return quotes.map(item=>({id:item.id,label:`${item.name} · ${item.vehicle}`}));return[];}
function populateSources(selected=""){const records=sourceRecords();sourceSelect.disabled=sourceType.value==="manual";sourceSelect.innerHTML=`<option value="">None selected</option>${records.map(item=>`<option value="${escapeHtml(item.id)}" ${String(item.id)===String(selected)?"selected":""}>${escapeHtml(item.label)}</option>`).join("")}`;}
function invoiceDefaults(invoice){const hold=invoice.deposit_method==="authorization_hold";const depositStatus=!Number(invoice.refundable_deposit)?"not_required":hold?(invoice.deposit_hold_status==="authorized"?"held":invoice.deposit_hold_status==="released"?"released":"pending"):"charged";return{source_type:"invoice",source_id:invoice.id,customer_name:invoice.customer_name||"",customer_email:invoice.customer_email||"",customer_phone:invoice.customer_phone||"",customer_address:invoice.customer_address||"",driver_name:invoice.customer_name||"",vehicle_name:invoice.vehicle_name||"",rental_start:invoice.rental_start||"",rental_end:invoice.rental_end||"",rental_days:invoice.rental_days||1,daily_rate:invoice.daily_rate||0,mileage_allowance:invoice.mileage_allowance||"100 miles/day",overage_rate:Number(String(invoice.overage_rate||"").replace(/[^0-9.]/g,""))||0,refundable_deposit:invoice.refundable_deposit||0,payment_status:invoice.status==="paid"?"paid":invoice.status==="partially_paid"?"partial":"unpaid",amount_paid:invoice.amount_paid||0,payment_method:invoice.payment_method||"stripe",payment_reference:invoice.payment_reference||"",deposit_status:depositStatus,terms:DEFAULT_TERMS};}
function applySource(){if(sourceType.value==="invoice"){const invoice=invoices.find(item=>String(item.id)===sourceSelect.value);if(!invoice)return;const values=invoiceDefaults(invoice);for(const[name,value]of Object.entries(values))if(form.elements[name])form.elements[name].value=value??"";calculateDays();renderMoney();return;}const q=quotes.find(item=>String(item.id)===sourceSelect.value);if(!q)return;form.elements.customer_name.value=q.name||"";form.elements.driver_name.value=q.name||"";form.elements.customer_email.value=q.email||"";form.elements.customer_phone.value=q.phone||"";form.elements.vehicle_name.value=q.vehicle||"";form.elements.rental_start.value=q.rental_date||"";form.elements.rental_days.value=q.quote_days||1;form.elements.daily_rate.value=q.quote_daily_rate||0;form.elements.refundable_deposit.value=q.quote_deposit||0;renderMoney();}
function renderList(){const q=String(search.value||"").toLowerCase(),rows=agreements.filter(a=>[a.agreement_number,a.customer_name,a.vehicle_name].some(v=>String(v||"").toLowerCase().includes(q)));list.innerHTML=rows.length?rows.map(a=>`<button class="invoice-list-item ${current?.id===a.id?"active":""}" type="button" data-select-agreement="${a.id}"><span><strong>${escapeHtml(a.agreement_number)}</strong><small>${escapeHtml(a.status.replaceAll("_"," "))}</small></span><b>${escapeHtml(a.customer_name)}</b><span><small>${escapeHtml(a.vehicle_name)}</small><strong>${money(a.rental_total)}</strong></span></button>`).join(""):`<p class="admin-empty">No matching agreements.</p>`;const active=agreements.filter(a=>["signed","vehicle_out","returned"].includes(a.status));kpis.innerHTML=`<article><span>Total</span><strong>${agreements.length}</strong></article><article><span>Awaiting signature</span><strong>${agreements.filter(a=>a.status==="draft").length}</strong></article><article><span>Active rentals</span><strong>${active.length}</strong></article><article><span>Completed</span><strong>${agreements.filter(a=>a.status==="completed").length}</strong></article>`;}
function stageRank(s){return {draft:0,signed:1,vehicle_out:2,returned:3,completed:4}[s]??0;}
function renderStages(){const state=current?.status||"draft",rank=stageRank(state);document.querySelectorAll(".agreement-stepper li").forEach((li,i)=>{li.classList.toggle("done",i<rank);li.classList.toggle("active",i===rank);});$("[data-agreement-stage=signature]").hidden=!current||rank>0;$("[data-agreement-stage=pickup]").hidden=!current||state!=="signed";$("[data-agreement-stage=return]").hidden=!current||state!=="vehicle_out";$("[data-agreement-stage=deposit]").hidden=!current||state!=="returned";$("[data-delete-agreement]").hidden=!current||role!=="owner"||state!=="draft";}
function clearSignature(){const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#17120c";ctx.lineWidth=3;ctx.lineCap="round";hasInk=false;}
function openAgreement(a=null){current=a?.id&&a?.agreement_number?a:null;empty.hidden=true;form.hidden=false;form.reset();const defaults=a||{source_type:"manual",rental_days:1,mileage_allowance:"100 miles/day",payment_status:"unpaid",payment_method:"stripe",deposit_status:"pending",terms:DEFAULT_TERMS};for(const [name,value] of Object.entries(defaults))if(form.elements[name]&&!["pickup_photo_paths","return_photo_paths"].includes(name))form.elements[name].value=value??"";sourceType.value=defaults.source_type||"manual";populateSources(defaults.source_id||"");title.textContent=current?.agreement_number||(defaults.source_type==="invoice"?"New agreement from invoice":"New agreement");badge.textContent=(current?.status||"draft").replaceAll("_"," ");badge.className=`invoice-status-badge ${current?.status||"draft"}`;clearSignature();renderStages();renderMoney();renderList();form.scrollIntoView({behavior:"smooth",block:"start"});}
async function load(force=false){if(loaded&&!force)return;setStatus("Loading agreements…");try{const [{agreements:rows,role:userRole},{data:q},{data:i}]=await Promise.all([api(),supabase.from("quote_requests").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("invoices").select("*").neq("status","void").order("created_at",{ascending:false}).limit(500)]);agreements=rows||[];quotes=q||[];invoices=i||[];role=userRole;loaded=true;renderList();setStatus("");if(current){const fresh=agreements.find(a=>a.id===current.id);if(fresh)openAgreement(fresh);}}catch(error){setStatus(error.message,"error");}}
async function uploadFiles(files,kind){if(!files?.length)return[];const uploaded=[];for(const file of files){const safe=file.name.replace(/[^a-z0-9._-]/gi,"-");const path=`${current.id}/${kind}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from("rental-documents").upload(path,file);if(error)throw error;uploaded.push(path);}return uploaded;}
async function save(){if(!form.reportValidity())return null;calculateDays();setStatus("Saving agreement…");let body=payload();const docs=[...form.elements.driver_documents.files];const result=await api("agreements",{method:current?"PATCH":"POST",body:JSON.stringify(body)});current=result.agreement;if(docs.length){const paths=await uploadFiles(docs,"driver-documents");body={...payload(),id:current.id,license_file_path:paths[0]||current.license_file_path,insurance_file_path:paths[1]||current.insurance_file_path};current=(await api("agreements",{method:"PATCH",body:JSON.stringify(body)})).agreement;}await load(true);openAgreement(current);setStatus("Agreement saved.","success");return current;}
async function action(name,extra={}){if(!current)throw new Error("Save the agreement first.");setStatus("Saving workflow step…");const result=await api("agreements",{method:"POST",body:JSON.stringify({action:name,id:current.id,...extra})});current=result.agreement;await load(true);openAgreement(current);setStatus("Workflow step completed.","success");}

form?.addEventListener("submit",async(e)=>{e.preventDefault();try{await save();}catch(error){setStatus(error.message,"error");}});
$("[data-new-agreement]")?.addEventListener("click",()=>openAgreement());
$("[data-crm-section=agreements]")?.addEventListener("click",()=>load());
search?.addEventListener("input",renderList);list?.addEventListener("click",e=>{const button=e.target.closest("[data-select-agreement]");if(button)openAgreement(agreements.find(a=>a.id===button.dataset.selectAgreement));});
sourceType?.addEventListener("change",()=>populateSources());sourceSelect?.addEventListener("change",applySource);
window.addEventListener("prestige:start-agreement",async(event)=>{try{const invoice=event.detail?.invoice;if(!invoice?.id)throw new Error("Save the invoice before continuing.");await load(true);const existing=agreements.find(item=>item.source_type==="invoice"&&String(item.source_id)===String(invoice.id));if(existing){openAgreement(existing);setStatus(`${existing.agreement_number} is already connected to this invoice.`,"success");return;}openAgreement(invoiceDefaults(invoice));setStatus(`Invoice ${invoice.invoice_number} carried forward. Review the agreement, then save it before collecting the signature.`,"success");}catch(error){setStatus(error.message,"error");}});
window.addEventListener("prestige:open-agreement",async(event)=>{try{await load(true);const agreement=agreements.find(item=>String(item.id)===String(event.detail?.id));if(!agreement)throw new Error("Agreement not found.");openAgreement(agreement);}catch(error){setStatus(error.message,"error");}});
form?.elements.rental_start.addEventListener("change",calculateDays);form?.elements.rental_end.addEventListener("change",calculateDays);form?.elements.rental_days.addEventListener("input",renderMoney);form?.elements.daily_rate.addEventListener("input",renderMoney);form?.elements.refundable_deposit.addEventListener("input",renderMoney);
canvas?.addEventListener("pointerdown",e=>{drawing=true;hasInk=true;canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),ctx=canvas.getContext("2d");ctx.beginPath();ctx.moveTo((e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height);});canvas?.addEventListener("pointermove",e=>{if(!drawing)return;const r=canvas.getBoundingClientRect();canvas.getContext("2d").lineTo((e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height);canvas.getContext("2d").stroke();});canvas?.addEventListener("pointerup",()=>drawing=false);canvas?.addEventListener("pointercancel",()=>drawing=false);$("[data-clear-signature]")?.addEventListener("click",clearSignature);
$("[data-sign-agreement]")?.addEventListener("click",async()=>{try{if(!hasInk)throw new Error("Ask the customer to draw their signature first.");if(!form.elements.signature_name.value.trim())throw new Error("Enter the signer’s full name.");const signatureName=form.elements.signature_name.value,signatureData=canvas.toDataURL("image/png");await save();await action("sign",{signature_name:signatureName,signature_data:signatureData});}catch(error){setStatus(error.message,"error");}});
$("[data-complete-pickup]")?.addEventListener("click",async()=>{try{const paths=await uploadFiles([...form.elements.pickup_photos.files],"pickup");await action("pickup",{pickup_mileage:form.elements.pickup_mileage.value,pickup_fuel:form.elements.pickup_fuel.value,pickup_notes:form.elements.pickup_notes.value,pickup_photo_paths:[...(current.pickup_photo_paths||[]),...paths]});}catch(error){setStatus(error.message,"error");}});
$("[data-complete-return]")?.addEventListener("click",async()=>{try{const paths=await uploadFiles([...form.elements.return_photos.files],"return");const fields=["return_mileage","return_fuel","return_notes","mileage_charge","fuel_charge","tolls_charge","damage_charge","other_charge","other_charge_label"],body={return_photo_paths:[...(current.return_photo_paths||[]),...paths]};fields.forEach(n=>body[n]=form.elements[n].value);await action("return",body);}catch(error){setStatus(error.message,"error");}});
$("[data-resolve-deposit]")?.addEventListener("click",async()=>{try{if(!confirm("Confirm you handled the release or deduction in Stripe and want to complete this rental?"))return;await action("resolve_deposit",{deposit_deduction:form.elements.deposit_deduction.value,deposit_resolution_note:form.elements.deposit_resolution_note.value});}catch(error){setStatus(error.message,"error");}});
$("[data-download-agreement]")?.addEventListener("click",async()=>{try{const saved=await save();const response=await api(`agreement-pdf?id=${encodeURIComponent(saved.id)}`);const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${saved.agreement_number}.pdf`;link.click();URL.revokeObjectURL(url);setStatus("Agreement PDF downloaded.","success");}catch(error){setStatus(error.message,"error");}});
$("[data-delete-agreement]")?.addEventListener("click",async()=>{try{if(!current||!confirm(`Delete draft ${current.agreement_number}? This cannot be undone.`))return;await api(`agreements?id=${encodeURIComponent(current.id)}`,{method:"DELETE"});current=null;form.hidden=true;empty.hidden=false;await load(true);setStatus("Draft deleted.","success");}catch(error){setStatus(error.message,"error");}});
supabase.auth.onAuthStateChange((event,session)=>{if(!session){loaded=false;agreements=[];}else if($("[data-section-panel=agreements]")?.classList.contains("active"))load();});
clearSignature();
