const MAX_LISTING_PHOTOS = 3;

const gallery = (slug, count) =>
  Array.from({ length: Math.min(count, MAX_LISTING_PHOTOS) }, (_, index) => `/assets/fleet-galleries/${slug}/${String(index + 1).padStart(2, "0")}.jpg`);

export const fleet = [
  {
    slug: "2021-bmw-m3-comp",
    name: "2021 BMW M3 Comp",
    make: "BMW",
    model: "M3 Comp",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 395,
    competitorPrice: 445,
    competitorName: "Prometheus Exotics",
    competitorUrl: "https://prometheusexotics.com/locations/south-county",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "Blue exterior / Silverstone interior",
    summary: "A sharp, executive performance sedan with carbon exterior upgrades and a tuned exhaust note.",
    image: "/assets/fleet/2021-bmw-m3-comp.jpg?v=sharp-20260620",
    gallery: gallery("2021-bmw-m3-comp", 5),
    tags: ["Carbon exterior", "Silverstone interior", "$375.00 3-5 days", "$350.00 6-7 days"],
    details: ["Carbon exterior package", "Performance exhaust", "Four-door daily usability", "Great for OC, Irvine, Newport, and LA delivery"],
  },
  {
    slug: "2022-porsche-911-carrera",
    name: "2022 Porsche 911 Carrera",
    make: "Porsche",
    model: "911 Carrera",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 350,
    competitorPrice: 400,
    competitorName: "Agera Rental",
    competitorUrl: "https://agerarental.com/",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "Red",
    summary: "A clean red 911 with a carbon wing and upgraded exhaust for a refined but unmistakable arrival.",
    image: "/assets/fleet/2022-porsche-911-carrera.jpg",
    gallery: gallery("2022-porsche-911-carrera", 5),
    tags: ["Carbon wing", "Upgraded exhaust", "$325.00 3-5 days", "$300.00 6-7 days"],
    details: ["Iconic 911 silhouette", "Carbon wing", "Upgraded exhaust", "Ideal for dinners, coast drives, and weekend bookings"],
  },
  {
    slug: "2017-audi-r8",
    name: "2017 Audi R8",
    make: "Audi",
    model: "R8",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 649,
    competitorPrice: 699,
    competitorName: "777 Exotics",
    competitorUrl: "https://777exotics.com/vehicle-types/exotic-rentals/",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "Matte black",
    summary: "A matte black R8 with carbon, exhaust, and tune work that brings supercar presence without shouting.",
    image: "/assets/fleet/2017-audi-r8.jpg?v=sharp-20260620",
    gallery: gallery("2017-audi-r8", 5),
    tags: ["Matte black", "Carbon", "Exhaust + tune", "$600.00 3-5 days"],
    details: ["Matte black finish", "Carbon accents", "Performance exhaust and tune", "Strong fit for nightlife, shoots, and Beverly Hills delivery"],
  },
  {
    slug: "2015-lamborghini-huracan-lp-610-4",
    name: "2015 Lamborghini Huracan LP-610-4",
    make: "Lamborghini",
    model: "Huracan LP-610-4",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 849,
    competitorPrice: 899,
    competitorName: "777 Exotics",
    competitorUrl: "https://777exotics.com/vehicle-types/exotic-rentals/",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "British Racing Green / red interior",
    summary: "A full-build Huracan with a 1016 kit, LAB Build upgrades, wheels, exhaust, tune, and carbon throughout.",
    image: "/assets/fleet/2015-lamborghini-huracan-lp-610-4.jpg",
    gallery: gallery("2015-lamborghini-huracan-lp-610-4", 5),
    tags: ["1016 kit", "LAB Build", "Carbon everywhere", "$800.00 3-5 days"],
    details: ["Full 1016 kit", "LAB Build upgrades", "Wheels, exhaust, and tune", "Red interior with major visual impact"],
  },
  {
    slug: "2022-lamborghini-huracan",
    name: "2022 Lamborghini Huracan",
    make: "Lamborghini",
    model: "Huracan",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 945,
    competitorPrice: 995,
    competitorName: "Peacock Rentals",
    competitorUrl: "https://peacock-rentals.com/orange-county",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "Blue convertible",
    summary: "A blue Huracan convertible built for coastal drives, VIP entrances, and open-air supercar moments.",
    image: "/assets/fleet/2022-lamborghini-huracan.jpg",
    gallery: gallery("2022-lamborghini-huracan", 1),
    tags: ["Convertible", "Blue exterior", "$895.00 3-5 days", "$850.00 6-7 days"],
    details: ["Open-air Lamborghini experience", "Blue exterior", "Strong hero car for Malibu and Newport Beach", "More photos can be added when available"],
  },
  {
    slug: "2016-ferrari-488-gtb",
    name: "2016 Ferrari 488 GTB",
    make: "Ferrari",
    model: "488 GTB",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 949,
    competitorPrice: 999,
    competitorName: "777 Exotics",
    competitorUrl: "https://777exotics.com/vehicle-types/exotic-rentals/",
    competitorCheckedAt: "2026-07-13",
    mileage: "100 miles/day",
    color: "Red",
    summary: "A red Ferrari 488 GTB with exhaust presence and timeless exotic-car energy.",
    image: "/assets/fleet/2016-ferrari-488-gtb.jpg",
    gallery: gallery("2016-ferrari-488-gtb", 5),
    tags: ["Red Ferrari", "Exhaust", "$900.00 3-5 days", "$850.00 6-7 days"],
    details: ["Ferrari V8 presence", "Red exterior", "Exhaust upgrade", "Best for weddings, nightlife, content, and VIP arrivals"],
  },
  {
    slug: "2018-mclaren-570s-spider",
    name: "2018 McLaren 570s Spider",
    make: "McLaren",
    model: "570s Spider",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 650,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "A blue McLaren Spider with downpipes, exhaust, tune, and carbon details for a rawer supercar feel.",
    image: "/assets/fleet/2018-mclaren-570s-spider.jpg?v=sharp-20260620",
    gallery: gallery("2018-mclaren-570s-spider", 4),
    tags: ["Spider", "Downpipes", "Exhaust + tune", "$600.00 3-5 days"],
    details: ["Convertible Spider body", "Full downpipes", "Exhaust and tune", "Carbon details with dramatic door presentation"],
  },
  {
    slug: "2019-mercedes-g63-amg",
    name: "2019 Mercedes G63 AMG",
    make: "Mercedes",
    model: "G63 AMG",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 400,
    mileage: "100 miles/day",
    color: "Matte black / white interior",
    summary: "A VIP SUV booking option with matte black presence and a white interior specification.",
    image: "/assets/fleet/2022-mercedes-gle53-amg.jpg?v=sharp-20260620",
    gallery: gallery("2019-mercedes-g63-amg", 1),
    tags: ["Matte black", "White interior", "$350.00 3-5 days", "$325.00 6-7 days"],
    details: ["Luxury SUV profile", "Matte black look", "White interior", "Exact G63 photos can be swapped in when available"],
  },
  {
    slug: "2022-mercedes-gle53-amg",
    name: "2022 Mercedes GLE53 AMG",
    make: "Mercedes",
    model: "GLE53 AMG",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 300,
    mileage: "100 miles/day",
    color: "Matte black",
    summary: "A 100k-spec AMG SUV with massaging seats and a polished matte-black look.",
    image: "/assets/fleet/2022-mercedes-gle53-amg.jpg?v=sharp-20260620",
    gallery: gallery("2022-mercedes-gle53-amg", 5),
    tags: ["Matte black", "Massaging seats", "100k spec", "$250.00 3-5 days"],
    details: ["AMG SUV comfort", "Massaging seats", "100k-spec build", "Great for LAX/SNA delivery and executive transport"],
  },
  {
    slug: "2022-cadillac-escalade",
    name: "2022 Cadillac Escalade",
    make: "Cadillac",
    model: "Escalade",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 300,
    mileage: "100 miles/day",
    color: "Dark blue",
    summary: "A dark blue Escalade with captain's chairs for groups, events, airport delivery, and VIP comfort.",
    image: "/assets/fleet/2022-cadillac-escalade.jpg?v=sharp-20260620",
    gallery: gallery("2022-cadillac-escalade", 5),
    tags: ["Captain's chairs", "Dark blue", "$250.00 3-5 days", "$200.00 6-7 days"],
    details: ["Captain's chairs", "Luxury full-size SUV", "Ideal for groups and event logistics", "Comfortable for LAX/SNA arrivals"],
  },
  {
    slug: "2026-ford-f150-raptor",
    name: "2026 Ford F150 Raptor",
    make: "Ford",
    model: "F150 Raptor",
    category: "suv luxury",
    categoryLabel: "Performance truck",
    price: 250,
    mileage: "100 miles/day",
    color: "Shelter Green",
    summary: "A Shelter Green Raptor with leveling kit, wheels, and a high-spec truck presence.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2026-ford-f150-raptor", 1),
    tags: ["Shelter Green", "Level kit + wheels", "90k spec", "$200.00 3-5 days"],
    details: ["Level kit and wheels", "90k-spec truck", "Great for lifestyle shoots and statement arrivals", "Exact Raptor photos can be added when available"],
  },
  {
    slug: "2020-lamborghini-urus",
    name: "2020 Lamborghini Urus",
    make: "Lamborghini",
    model: "Urus",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 750,
    mileage: "100 miles/day",
    color: "Matte black / orange interior",
    summary: "A matte black Urus with orange interior and full turbo-back Akrapovic exhaust.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2020-lamborghini-urus", 1),
    tags: ["Matte black", "Orange interior", "Akrapovic exhaust", "$700.00 3-5 days"],
    details: ["Full turbo-back Akrapovic exhaust", "Orange interior", "Matte black look", "Exact Urus photos can be added when available"],
  },
  {
    slug: "2024-bmw-m4-comp",
    name: "2024 BMW M4-Comp",
    make: "BMW",
    model: "M4-Comp",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 300,
    mileage: "100 miles/day",
    color: "Skyscraper gray / ivory white interior",
    summary: "A Skyscraper Gray M4 Comp with ivory white interior, RVNG exhaust, lowering springs, and spacers.",
    image: "/assets/fleet/2024-bmw-m4-comp.jpg",
    gallery: gallery("2024-bmw-m4-comp", 5),
    tags: ["RVNG exhaust", "Lowering springs", "Ivory interior", "$250.00 3-5 days"],
    details: ["RVNG exhaust", "Lowering springs and spacers", "Ivory white interior", "A strong coupe option for OC and LA bookings"],
  },
  {
    slug: "2026-chevy-c8-corvette",
    name: "2026 Chevy C8 Corvette",
    make: "Chevy",
    model: "C8 Corvette",
    category: "supercar",
    categoryLabel: "Sports car",
    price: 250,
    mileage: "100 miles/day",
    color: "Torch Red",
    summary: "A Torch Red C8 Corvette with exhaust and splitter for accessible mid-engine performance.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2026-chevy-c8-corvette", 1),
    tags: ["Torch Red", "Exhaust", "Splitter", "$225.00 3-5 days"],
    details: ["Mid-engine Corvette platform", "Torch Red exterior", "Exhaust and splitter", "Exact C8 photos can be added when available"],
  },
  // Pixieset fleet import - 2026-07-07
  {
    slug: "mercedes-c63",
    name: "Mercedes C63",
    make: "Mercedes",
    model: "C63",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Mercedes C63 added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-c63.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-c63/01.jpg", "/assets/fleet-galleries/mercedes-c63/02.jpg", "/assets/fleet-galleries/mercedes-c63/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-pink",
    name: "Lamborghini Huracan (Pink)",
    make: "Lamborghini",
    model: "Huracan (Pink)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Pink",
    summary: "Lamborghini Huracan (Pink) in Pink added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-pink.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-pink/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-pink/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-pink/03.jpg"],
    tags: ["Supercar", "Pink", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m4-x-drive-blue",
    name: "BMW M4 X-Drive (Blue)",
    make: "BMW",
    model: "M4 X-Drive (Blue)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "BMW M4 X-Drive (Blue) in Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m4-x-drive-blue.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m4-x-drive-blue/01.jpg", "/assets/fleet-galleries/bmw-m4-x-drive-blue/02.jpg", "/assets/fleet-galleries/bmw-m4-x-drive-blue/03.jpg"],
    tags: ["Sports luxury", "Blue", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-white",
    name: "Lamborghini Urus (White)",
    make: "Lamborghini",
    model: "Urus (White)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "White",
    summary: "Lamborghini Urus (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-white.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-white/01.jpg", "/assets/fleet-galleries/lamborghini-urus-white/02.jpg", "/assets/fleet-galleries/lamborghini-urus-white/03.jpg"],
    tags: ["Super SUV", "White", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-brabus-g-wagon",
    name: "Mercedes Brabus G-Wagon",
    make: "Mercedes",
    model: "Brabus G-Wagon",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 550,
    mileage: "100 miles/day",
    color: "",
    summary: "Mercedes Brabus G-Wagon added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-brabus-g-wagon.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-brabus-g-wagon/01.jpg", "/assets/fleet-galleries/mercedes-brabus-g-wagon/02.jpg", "/assets/fleet-galleries/mercedes-brabus-g-wagon/03.jpg"],
    tags: ["Luxury SUV", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-orange",
    name: "Corvette C8 (Orange)",
    make: "Chevy",
    model: "Corvette C8 (Orange)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Orange",
    summary: "Corvette C8 (Orange) in Orange added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-orange.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-orange/01.jpg", "/assets/fleet-galleries/corvette-c8-orange/02.jpg", "/assets/fleet-galleries/corvette-c8-orange/03.jpg"],
    tags: ["Supercar", "Orange", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "land-rover-defender",
    name: "Land Rover Defender",
    make: "Land Rover",
    model: "Defender",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 400,
    mileage: "100 miles/day",
    color: "",
    summary: "Land Rover Defender added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/land-rover-defender.jpg",
    gallery: ["/assets/fleet-galleries/land-rover-defender/01.jpg", "/assets/fleet-galleries/land-rover-defender/02.jpg", "/assets/fleet-galleries/land-rover-defender/03.jpg"],
    tags: ["Luxury SUV", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "land-rover-range-rover",
    name: "Land Rover Range Rover",
    make: "Land Rover",
    model: "Range Rover",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 400,
    mileage: "100 miles/day",
    color: "",
    summary: "Land Rover Range Rover added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/land-rover-range-rover.jpg",
    gallery: ["/assets/fleet-galleries/land-rover-range-rover/01.jpg", "/assets/fleet-galleries/land-rover-range-rover/02.jpg", "/assets/fleet-galleries/land-rover-range-rover/03.jpg"],
    tags: ["Luxury SUV", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m3-gloss-grey",
    name: "BMW M3 (Gloss Grey)",
    make: "BMW",
    model: "M3 (Gloss Grey)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Gloss Grey",
    summary: "BMW M3 (Gloss Grey) in Gloss Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m3-gloss-grey.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m3-gloss-grey/01.jpg", "/assets/fleet-galleries/bmw-m3-gloss-grey/02.jpg", "/assets/fleet-galleries/bmw-m3-gloss-grey/03.jpg"],
    tags: ["Sports luxury", "Gloss Grey", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "tesla-cybertruck",
    name: "Tesla Cybertruck",
    make: "Tesla",
    model: "Cybertruck",
    category: "suv luxury",
    categoryLabel: "Electric truck",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Tesla Cybertruck added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/tesla-cybertruck.jpg",
    gallery: ["/assets/fleet-galleries/tesla-cybertruck/01.jpg", "/assets/fleet-galleries/tesla-cybertruck/02.jpg", "/assets/fleet-galleries/tesla-cybertruck/03.jpg"],
    tags: ["Electric truck", "Pixieset import", "Rate to confirm"],
    details: ["Electric truck option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m5-dark-grey",
    name: "BMW M5 (Dark Grey)",
    make: "BMW",
    model: "M5 (Dark Grey)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Dark Grey",
    summary: "BMW M5 (Dark Grey) in Dark Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m5-dark-grey.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m5-dark-grey/01.jpg", "/assets/fleet-galleries/bmw-m5-dark-grey/02.jpg", "/assets/fleet-galleries/bmw-m5-dark-grey/03.jpg"],
    tags: ["Sports luxury", "Dark Grey", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m3-frozen-white",
    name: "BMW M3 (Frozen White)",
    make: "BMW",
    model: "M3 (Frozen White)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Frozen White",
    summary: "BMW M3 (Frozen White) in Frozen White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m3-frozen-white.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m3-frozen-white/01.jpg", "/assets/fleet-galleries/bmw-m3-frozen-white/02.jpg", "/assets/fleet-galleries/bmw-m3-frozen-white/03.jpg"],
    tags: ["Sports luxury", "Frozen White", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m3cs",
    name: "BMW M3cs",
    make: "BMW",
    model: "M3cs",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "BMW M3cs added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m3cs.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m3cs/01.jpg", "/assets/fleet-galleries/bmw-m3cs/02.jpg", "/assets/fleet-galleries/bmw-m3cs/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-z06-grey",
    name: "Corvette C8 Z06 (Grey)",
    make: "Chevy",
    model: "Corvette C8 Z06 (Grey)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Grey",
    summary: "Corvette C8 Z06 (Grey) in Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-z06-grey.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-z06-grey/01.jpg", "/assets/fleet-galleries/corvette-c8-z06-grey/02.jpg", "/assets/fleet-galleries/corvette-c8-z06-grey/03.jpg"],
    tags: ["Supercar", "Grey", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m3-isle-man-green",
    name: "BMW M3 (Isle Man Green)",
    make: "BMW",
    model: "M3 (Isle Man Green)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Isle Man Green",
    summary: "BMW M3 (Isle Man Green) in Isle Man Green added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m3-isle-man-green.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m3-isle-man-green/01.jpg", "/assets/fleet-galleries/bmw-m3-isle-man-green/02.jpg", "/assets/fleet-galleries/bmw-m3-isle-man-green/03.jpg"],
    tags: ["Sports luxury", "Isle Man Green", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mclaren-artura-black",
    name: "McLaren Artura (Black)",
    make: "McLaren",
    model: "Artura (Black)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Black",
    summary: "McLaren Artura (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mclaren-artura-black.jpg",
    gallery: ["/assets/fleet-galleries/mclaren-artura-black/01.jpg", "/assets/fleet-galleries/mclaren-artura-black/02.jpg", "/assets/fleet-galleries/mclaren-artura-black/03.jpg"],
    tags: ["Supercar", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mclaren-artura-silver",
    name: "McLaren Artura (Silver)",
    make: "McLaren",
    model: "Artura (Silver)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Silver",
    summary: "McLaren Artura (Silver) in Silver added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mclaren-artura-silver.jpg",
    gallery: ["/assets/fleet-galleries/mclaren-artura-silver/01.jpg", "/assets/fleet-galleries/mclaren-artura-silver/02.jpg", "/assets/fleet-galleries/mclaren-artura-silver/03.jpg"],
    tags: ["Supercar", "Silver", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bentley-continental-gtc-black",
    name: "Bentley Continental GTC (Black)",
    make: "Bentley",
    model: "Continental GTC (Black)",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 650,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Bentley Continental GTC (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bentley-continental-gtc-black.jpg",
    gallery: ["/assets/fleet-galleries/bentley-continental-gtc-black/01.jpg", "/assets/fleet-galleries/bentley-continental-gtc-black/02.jpg", "/assets/fleet-galleries/bentley-continental-gtc-black/03.jpg"],
    tags: ["Convertible", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-perf",
    name: "Lamborghini Huracan Perf.",
    make: "Lamborghini",
    model: "Huracan Perf.",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "",
    summary: "Lamborghini Huracan Perf. added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-perf.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-perf/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-perf/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-perf/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "land-rover-sport-white",
    name: "Land Rover Sport (White)",
    make: "Land Rover",
    model: "Sport (White)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "White",
    summary: "Land Rover Sport (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/land-rover-sport-white.jpg",
    gallery: ["/assets/fleet-galleries/land-rover-sport-white/01.jpg", "/assets/fleet-galleries/land-rover-sport-white/02.jpg", "/assets/fleet-galleries/land-rover-sport-white/03.jpg"],
    tags: ["Supercar", "White", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bentley-continental-gtc",
    name: "Bentley Continental GTC",
    make: "Bentley",
    model: "Continental GTC",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 650,
    mileage: "100 miles/day",
    color: "",
    summary: "Bentley Continental GTC added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bentley-continental-gtc.jpg",
    gallery: ["/assets/fleet-galleries/bentley-continental-gtc/01.jpg", "/assets/fleet-galleries/bentley-continental-gtc/02.jpg", "/assets/fleet-galleries/bentley-continental-gtc/03.jpg"],
    tags: ["Convertible", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-modded-black",
    name: "Corvette C8 Modded (Black)",
    make: "Chevy",
    model: "Corvette C8 Modded (Black)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Corvette C8 Modded (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-modded-black.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-modded-black/01.jpg", "/assets/fleet-galleries/corvette-c8-modded-black/02.jpg", "/assets/fleet-galleries/corvette-c8-modded-black/03.jpg"],
    tags: ["Supercar", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m4-comp-sprite",
    name: "BMW M4 Comp (Sprite)",
    make: "BMW",
    model: "M4 Comp (Sprite)",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "Sprite",
    summary: "BMW M4 Comp (Sprite) in Sprite added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m4-comp-sprite.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m4-comp-sprite/01.jpg", "/assets/fleet-galleries/bmw-m4-comp-sprite/02.jpg", "/assets/fleet-galleries/bmw-m4-comp-sprite/03.jpg"],
    tags: ["Sports luxury", "Sprite", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-maybach-gls-600-black",
    name: "Mercedes-Maybach GLS 600 (Black)",
    make: "Mercedes-Maybach",
    model: "GLS 600 (Black)",
    category: "suv luxury",
    categoryLabel: "Ultra luxury SUV",
    price: 700,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Mercedes-Maybach GLS 600 (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-maybach-gls-600-black.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-maybach-gls-600-black/01.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-black/02.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-black/03.jpg"],
    tags: ["Ultra luxury SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Ultra luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-s-class-amg-s63",
    name: "Mercedes S Class AMG S63",
    make: "Mercedes",
    model: "S Class AMG S63",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Mercedes S Class AMG S63 added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-s-class-amg-s63.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-s-class-amg-s63/01.jpg", "/assets/fleet-galleries/mercedes-s-class-amg-s63/02.jpg", "/assets/fleet-galleries/mercedes-s-class-amg-s63/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-black",
    name: "Lamborghini Urus (Black)",
    make: "Lamborghini",
    model: "Urus (Black)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Lamborghini Urus (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-black.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-black/01.jpg", "/assets/fleet-galleries/lamborghini-urus-black/02.jpg", "/assets/fleet-galleries/lamborghini-urus-black/03.jpg"],
    tags: ["Super SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-green",
    name: "Lamborghini Huracan (Green)",
    make: "Lamborghini",
    model: "Huracan (Green)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Green",
    summary: "Lamborghini Huracan (Green) in Green added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-green.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-green/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-green/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-green/03.jpg"],
    tags: ["Supercar", "Green", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m4-comp",
    name: "BMW M4 Comp",
    make: "BMW",
    model: "M4 Comp",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "BMW M4 Comp added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m4-comp.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m4-comp/01.jpg", "/assets/fleet-galleries/bmw-m4-comp/02.jpg", "/assets/fleet-galleries/bmw-m4-comp/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-amg-gt-r-green",
    name: "Mercedes AMG GT-R (Green)",
    make: "Mercedes AMG",
    model: "GT-R (Green)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 650,
    mileage: "100 miles/day",
    color: "Green",
    summary: "Mercedes AMG GT-R (Green) in Green added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-amg-gt-r-green.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-amg-gt-r-green/01.jpg", "/assets/fleet-galleries/mercedes-amg-gt-r-green/02.jpg", "/assets/fleet-galleries/mercedes-amg-gt-r-green/03.jpg"],
    tags: ["Supercar", "Green", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "ferrari-f8",
    name: "Ferrari F8",
    make: "Ferrari",
    model: "F8",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 950,
    mileage: "100 miles/day",
    color: "",
    summary: "Ferrari F8 added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/ferrari-f8.jpg",
    gallery: ["/assets/fleet-galleries/ferrari-f8/01.jpg", "/assets/fleet-galleries/ferrari-f8/02.jpg", "/assets/fleet-galleries/ferrari-f8/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "ferrari-488-spider-grey",
    name: "Ferrari 488 Spider (Grey)",
    make: "Ferrari",
    model: "488 Spider (Grey)",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 750,
    mileage: "100 miles/day",
    color: "Grey",
    summary: "Ferrari 488 Spider (Grey) in Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/ferrari-488-spider-grey.jpg",
    gallery: ["/assets/fleet-galleries/ferrari-488-spider-grey/01.jpg", "/assets/fleet-galleries/ferrari-488-spider-grey/02.jpg", "/assets/fleet-galleries/ferrari-488-spider-grey/03.jpg"],
    tags: ["Convertible", "Grey", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "ferrari-portofino",
    name: "Ferrari Portofino",
    make: "Ferrari",
    model: "Portofino",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 750,
    mileage: "100 miles/day",
    color: "",
    summary: "Ferrari Portofino added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/ferrari-portofino.jpg",
    gallery: ["/assets/fleet-galleries/ferrari-portofino/01.jpg", "/assets/fleet-galleries/ferrari-portofino/02.jpg", "/assets/fleet-galleries/ferrari-portofino/03.jpg"],
    tags: ["Convertible", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mclaren-570s",
    name: "McLaren 570s",
    make: "McLaren",
    model: "570s",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 750,
    mileage: "100 miles/day",
    color: "",
    summary: "McLaren 570s added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mclaren-570s.jpg",
    gallery: ["/assets/fleet-galleries/mclaren-570s/01.jpg", "/assets/fleet-galleries/mclaren-570s/02.jpg", "/assets/fleet-galleries/mclaren-570s/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "cadillac-escalade-white",
    name: "Cadillac Escalade (White)",
    make: "Cadillac",
    model: "Escalade (White)",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 400,
    mileage: "100 miles/day",
    color: "White",
    summary: "Cadillac Escalade (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/cadillac-escalade-white.jpg",
    gallery: ["/assets/fleet-galleries/cadillac-escalade-white/01.jpg", "/assets/fleet-galleries/cadillac-escalade-white/02.jpg", "/assets/fleet-galleries/cadillac-escalade-white/03.jpg"],
    tags: ["Luxury SUV", "White", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-grey",
    name: "Lamborghini Urus (Grey)",
    make: "Lamborghini",
    model: "Urus (Grey)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "Grey",
    summary: "Lamborghini Urus (Grey) in Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-grey.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-grey/01.jpg", "/assets/fleet-galleries/lamborghini-urus-grey/02.jpg", "/assets/fleet-galleries/lamborghini-urus-grey/03.jpg"],
    tags: ["Super SUV", "Grey", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-widebody-urus-black",
    name: "Lamborghini Widebody Urus (Black)",
    make: "Lamborghini",
    model: "Widebody Urus (Black)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Lamborghini Widebody Urus (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-widebody-urus-black.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-widebody-urus-black/01.jpg", "/assets/fleet-galleries/lamborghini-widebody-urus-black/02.jpg", "/assets/fleet-galleries/lamborghini-widebody-urus-black/03.jpg"],
    tags: ["Super SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-g-wagon-black",
    name: "Mercedes G-Wagon (Black)",
    make: "Mercedes",
    model: "G-Wagon (Black)",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 550,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Mercedes G-Wagon (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-g-wagon-black.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-g-wagon-black/01.jpg", "/assets/fleet-galleries/mercedes-g-wagon-black/02.jpg", "/assets/fleet-galleries/mercedes-g-wagon-black/03.jpg"],
    tags: ["Luxury SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-z06-black",
    name: "Corvette C8 Z06 (Black)",
    make: "Chevy",
    model: "Corvette C8 Z06 (Black)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Corvette C8 Z06 (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-z06-black.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-z06-black/01.jpg", "/assets/fleet-galleries/corvette-c8-z06-black/02.jpg", "/assets/fleet-galleries/corvette-c8-z06-black/03.jpg"],
    tags: ["Supercar", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-performante-white",
    name: "Lamborghini Urus Performante (White)",
    make: "Lamborghini",
    model: "Urus Performante (White)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 1000,
    mileage: "100 miles/day",
    color: "White",
    summary: "Lamborghini Urus Performante (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-performante-white.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-performante-white/01.jpg", "/assets/fleet-galleries/lamborghini-urus-performante-white/02.jpg", "/assets/fleet-galleries/lamborghini-urus-performante-white/03.jpg"],
    tags: ["Super SUV", "White", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "porsche-macan-black",
    name: "Porsche Macan (Black)",
    make: "Porsche",
    model: "Macan (Black)",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 300,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Porsche Macan (Black) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/porsche-macan-black.jpg",
    gallery: ["/assets/fleet-galleries/porsche-macan-black/01.jpg", "/assets/fleet-galleries/porsche-macan-black/02.jpg", "/assets/fleet-galleries/porsche-macan-black/03.jpg"],
    tags: ["Luxury SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bentley-continental",
    name: "Bentley Continental",
    make: "Bentley",
    model: "Continental",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 650,
    mileage: "100 miles/day",
    color: "",
    summary: "Bentley Continental added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bentley-continental.jpg",
    gallery: ["/assets/fleet-galleries/bentley-continental/01.jpg", "/assets/fleet-galleries/bentley-continental/02.jpg", "/assets/fleet-galleries/bentley-continental/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lotus-emira-green",
    name: "Lotus Emira (Green)",
    make: "Lotus",
    model: "Emira (Green)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 450,
    mileage: "100 miles/day",
    color: "Green",
    summary: "Lotus Emira (Green) in Green added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lotus-emira-green.jpg",
    gallery: ["/assets/fleet-galleries/lotus-emira-green/01.jpg", "/assets/fleet-galleries/lotus-emira-green/02.jpg", "/assets/fleet-galleries/lotus-emira-green/03.jpg"],
    tags: ["Supercar", "Green", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "porsche-911-carrera-gts",
    name: "Porsche 911 Carrera GTS",
    make: "Porsche",
    model: "911 Carrera GTS",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "",
    summary: "Porsche 911 Carrera GTS added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/porsche-911-carrera-gts.jpg",
    gallery: ["/assets/fleet-galleries/porsche-911-carrera-gts/01.jpg", "/assets/fleet-galleries/porsche-911-carrera-gts/02.jpg", "/assets/fleet-galleries/porsche-911-carrera-gts/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "porsche-911-carrera-red",
    name: "Porsche 911 Carrera (Red)",
    make: "Porsche",
    model: "911 Carrera (Red)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Red",
    summary: "Porsche 911 Carrera (Red) in Red added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/porsche-911-carrera-red.jpg",
    gallery: ["/assets/fleet-galleries/porsche-911-carrera-red/01.jpg", "/assets/fleet-galleries/porsche-911-carrera-red/02.jpg", "/assets/fleet-galleries/porsche-911-carrera-red/03.jpg"],
    tags: ["Supercar", "Red", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-blue",
    name: "Lamborghini Urus (Blue)",
    make: "Lamborghini",
    model: "Urus (Blue)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "Lamborghini Urus (Blue) in Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-blue.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-blue/01.jpg", "/assets/fleet-galleries/lamborghini-urus-blue/02.jpg", "/assets/fleet-galleries/lamborghini-urus-blue/03.jpg"],
    tags: ["Super SUV", "Blue", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-sv",
    name: "Lamborghini SV",
    make: "Lamborghini",
    model: "SV",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 1000,
    mileage: "100 miles/day",
    color: "",
    summary: "Lamborghini SV added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-sv.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-sv/01.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "porsche-panamera",
    name: "Porsche Panamera",
    make: "Porsche",
    model: "Panamera",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Porsche Panamera added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/porsche-panamera.jpg",
    gallery: ["/assets/fleet-galleries/porsche-panamera/01.jpg", "/assets/fleet-galleries/porsche-panamera/02.jpg", "/assets/fleet-galleries/porsche-panamera/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "tesla-plaid-model-s",
    name: "Tesla Plaid Model S",
    make: "Tesla",
    model: "Plaid Model S",
    category: "sports luxury",
    categoryLabel: "EV performance",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Tesla Plaid Model S added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/tesla-plaid-model-s.jpg",
    gallery: ["/assets/fleet-galleries/tesla-plaid-model-s/01.jpg", "/assets/fleet-galleries/tesla-plaid-model-s/02.jpg", "/assets/fleet-galleries/tesla-plaid-model-s/03.jpg"],
    tags: ["EV performance", "Pixieset import", "Rate to confirm"],
    details: ["EV performance option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "ferrari-488-gtb-yellow",
    name: "Ferrari 488 GTB (Yellow)",
    make: "Ferrari",
    model: "488 GTB (Yellow)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 750,
    mileage: "100 miles/day",
    color: "Yellow",
    summary: "Ferrari 488 GTB (Yellow) in Yellow added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/ferrari-488-gtb-yellow.jpg",
    gallery: ["/assets/fleet-galleries/ferrari-488-gtb-yellow/01.jpg", "/assets/fleet-galleries/ferrari-488-gtb-yellow/02.jpg", "/assets/fleet-galleries/ferrari-488-gtb-yellow/03.jpg"],
    tags: ["Supercar", "Yellow", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "porschepanamera",
    name: "Porsche Panamera",
    make: "Porsche",
    model: "Panamera",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "Porsche Panamera added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/porschepanamera.jpg",
    gallery: ["/assets/fleet-galleries/porschepanamera/01.jpg", "/assets/fleet-galleries/porschepanamera/02.jpg", "/assets/fleet-galleries/porschepanamera/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "audi-r8-black",
    name: "Audi R8 (BLACK)",
    make: "Audi",
    model: "R8 (BLACK)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Audi R8 (BLACK) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/audi-r8-black.jpg",
    gallery: ["/assets/fleet-galleries/audi-r8-black/01.jpg", "/assets/fleet-galleries/audi-r8-black/02.jpg", "/assets/fleet-galleries/audi-r8-black/03.jpg"],
    tags: ["Supercar", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-g-wagon-blue",
    name: "Mercedes G-Wagon (Blue)",
    make: "Mercedes",
    model: "G-Wagon (Blue)",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 550,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "Mercedes G-Wagon (Blue) in Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-g-wagon-blue.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-g-wagon-blue/01.jpg", "/assets/fleet-galleries/mercedes-g-wagon-blue/02.jpg", "/assets/fleet-galleries/mercedes-g-wagon-blue/03.jpg"],
    tags: ["Luxury SUV", "Blue", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-evo",
    name: "Lamborghini Huracan EVO",
    make: "Lamborghini",
    model: "Huracan EVO",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "",
    summary: "Lamborghini Huracan EVO added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-evo.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-evo/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-evo/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-evo/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-maybach-grey",
    name: "Mercedes Maybach (Grey)",
    make: "Mercedes",
    model: "Maybach (Grey)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 700,
    mileage: "100 miles/day",
    color: "Grey",
    summary: "Mercedes Maybach (Grey) in Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-maybach-grey.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-maybach-grey/01.jpg", "/assets/fleet-galleries/mercedes-maybach-grey/02.jpg", "/assets/fleet-galleries/mercedes-maybach-grey/03.jpg"],
    tags: ["Supercar", "Grey", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-z06-navy-blue",
    name: "Corvette C8 Z06 (Navy Blue)",
    make: "Chevy",
    model: "Corvette C8 Z06 (Navy Blue)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Navy Blue",
    summary: "Corvette C8 Z06 (Navy Blue) in Navy Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-z06-navy-blue.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-z06-navy-blue/01.jpg", "/assets/fleet-galleries/corvette-c8-z06-navy-blue/02.jpg", "/assets/fleet-galleries/corvette-c8-z06-navy-blue/03.jpg"],
    tags: ["Supercar", "Navy Blue", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m5-competition",
    name: "BMW M5 Competition",
    make: "BMW",
    model: "M5 Competition",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "BMW M5 Competition added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m5-competition.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m5-competition/01.jpg", "/assets/fleet-galleries/bmw-m5-competition/02.jpg", "/assets/fleet-galleries/bmw-m5-competition/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "rolls-royce-cullinan-white",
    name: "Rolls-Royce Cullinan (White)",
    make: "Rolls-Royce",
    model: "Cullinan (White)",
    category: "suv luxury",
    categoryLabel: "Ultra luxury SUV",
    price: 1200,
    mileage: "100 miles/day",
    color: "White",
    summary: "Rolls-Royce Cullinan (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/rolls-royce-cullinan-white.jpg",
    gallery: ["/assets/fleet-galleries/rolls-royce-cullinan-white/01.jpg", "/assets/fleet-galleries/rolls-royce-cullinan-white/02.jpg", "/assets/fleet-galleries/rolls-royce-cullinan-white/03.jpg"],
    tags: ["Ultra luxury SUV", "White", "Pixieset import", "Rate to confirm"],
    details: ["Ultra luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-blue",
    name: "Lamborghini Huracán (Blue)",
    make: "Lamborghini",
    model: "Huracán (Blue)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "Lamborghini Huracán (Blue) in Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-blue.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-blue/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-blue/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-blue/03.jpg"],
    tags: ["Supercar", "Blue", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bentley-continental-gt-convertible",
    name: "Bentley Continental GT Convertible",
    make: "Bentley",
    model: "Continental GT Convertible",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 650,
    mileage: "100 miles/day",
    color: "",
    summary: "Bentley Continental GT Convertible added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bentley-continental-gt-convertible.jpg",
    gallery: ["/assets/fleet-galleries/bentley-continental-gt-convertible/01.jpg", "/assets/fleet-galleries/bentley-continental-gt-convertible/02.jpg", "/assets/fleet-galleries/bentley-continental-gt-convertible/03.jpg"],
    tags: ["Convertible", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-spyder-white",
    name: "Lamborghini Huracán Spyder (White)",
    make: "Lamborghini",
    model: "Huracán Spyder (White)",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 500,
    mileage: "100 miles/day",
    color: "White",
    summary: "Lamborghini Huracán Spyder (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-spyder-white.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-spyder-white/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-spyder-white/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-spyder-white/03.jpg"],
    tags: ["Convertible", "White", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-amg-gt-63",
    name: "Mercedes AMG GT 63",
    make: "Mercedes AMG",
    model: "GT 63",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 500,
    mileage: "100 miles/day",
    color: "",
    summary: "Mercedes AMG GT 63 added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-amg-gt-63.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-amg-gt-63/01.jpg", "/assets/fleet-galleries/mercedes-amg-gt-63/02.jpg", "/assets/fleet-galleries/mercedes-amg-gt-63/03.jpg"],
    tags: ["Sports luxury", "Pixieset import", "Rate to confirm"],
    details: ["Sports luxury option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-black",
    name: "Corvette C8 (BLACK)",
    make: "Chevy",
    model: "Corvette C8 (BLACK)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Corvette C8 (BLACK) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-black.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-black/01.jpg", "/assets/fleet-galleries/corvette-c8-black/02.jpg", "/assets/fleet-galleries/corvette-c8-black/03.jpg"],
    tags: ["Supercar", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-urus-s-black",
    name: "Lamborghini Urus S (BLACK)",
    make: "Lamborghini",
    model: "Urus S (BLACK)",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 800,
    mileage: "100 miles/day",
    color: "Black",
    summary: "Lamborghini Urus S (BLACK) in Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-urus-s-black.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-urus-s-black/01.jpg", "/assets/fleet-galleries/lamborghini-urus-s-black/02.jpg", "/assets/fleet-galleries/lamborghini-urus-s-black/03.jpg"],
    tags: ["Super SUV", "Black", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-white",
    name: "Corvette C8 (White)",
    make: "Chevy",
    model: "Corvette C8 (White)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "White",
    summary: "Corvette C8 (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-white.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-white/01.jpg", "/assets/fleet-galleries/corvette-c8-white/02.jpg", "/assets/fleet-galleries/corvette-c8-white/03.jpg"],
    tags: ["Supercar", "White", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-g-wagon-silver",
    name: "Mercedes G-Wagon (Silver)",
    make: "Mercedes",
    model: "G-Wagon (Silver)",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 550,
    mileage: "100 miles/day",
    color: "Silver",
    summary: "Mercedes G-Wagon (Silver) in Silver added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-g-wagon-silver.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-g-wagon-silver/01.jpg", "/assets/fleet-galleries/mercedes-g-wagon-silver/02.jpg", "/assets/fleet-galleries/mercedes-g-wagon-silver/03.jpg"],
    tags: ["Luxury SUV", "Silver", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "cadillac-escalade-esv",
    name: "Cadillac Escalade ESV",
    make: "Cadillac",
    model: "Escalade ESV",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 1000,
    mileage: "100 miles/day",
    color: "",
    summary: "Cadillac Escalade ESV added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/cadillac-escalade-esv.jpg",
    gallery: ["/assets/fleet-galleries/cadillac-escalade-esv/01.jpg", "/assets/fleet-galleries/cadillac-escalade-esv/02.jpg", "/assets/fleet-galleries/cadillac-escalade-esv/03.jpg"],
    tags: ["Luxury SUV", "Pixieset import", "Rate to confirm"],
    details: ["Luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "ferrari-296-gtb",
    name: "Ferrari 296 GTB",
    make: "Ferrari",
    model: "296 GTB",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 950,
    mileage: "100 miles/day",
    color: "",
    summary: "Ferrari 296 GTB added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/ferrari-296-gtb.jpg",
    gallery: ["/assets/fleet-galleries/ferrari-296-gtb/01.jpg", "/assets/fleet-galleries/ferrari-296-gtb/02.jpg", "/assets/fleet-galleries/ferrari-296-gtb/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mclaren-720s-turquoise",
    name: "McLaren 720S (Turquoise)",
    make: "McLaren",
    model: "720S (Turquoise)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 950,
    mileage: "100 miles/day",
    color: "Turquoise",
    summary: "McLaren 720S (Turquoise) in Turquoise added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mclaren-720s-turquoise.jpg",
    gallery: ["/assets/fleet-galleries/mclaren-720s-turquoise/01.jpg", "/assets/fleet-galleries/mclaren-720s-turquoise/02.jpg", "/assets/fleet-galleries/mclaren-720s-turquoise/03.jpg"],
    tags: ["Supercar", "Turquoise", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "corvette-c8-charcoal-grey",
    name: "Corvette C8 (Charcoal Grey)",
    make: "Chevy",
    model: "Corvette C8 (Charcoal Grey)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Charcoal Grey",
    summary: "Corvette C8 (Charcoal Grey) in Charcoal Grey added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/corvette-c8-charcoal-grey.jpg",
    gallery: ["/assets/fleet-galleries/corvette-c8-charcoal-grey/01.jpg", "/assets/fleet-galleries/corvette-c8-charcoal-grey/02.jpg", "/assets/fleet-galleries/corvette-c8-charcoal-grey/03.jpg"],
    tags: ["Supercar", "Charcoal Grey", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "audi-r8-v10-spyder-white",
    name: "Audi R8 V10 Spyder (White)",
    make: "Audi",
    model: "R8 V10 Spyder (White)",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 800,
    mileage: "100 miles/day",
    color: "White",
    summary: "Audi R8 V10 Spyder (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/audi-r8-v10-spyder-white.jpg",
    gallery: ["/assets/fleet-galleries/audi-r8-v10-spyder-white/01.jpg", "/assets/fleet-galleries/audi-r8-v10-spyder-white/02.jpg", "/assets/fleet-galleries/audi-r8-v10-spyder-white/03.jpg"],
    tags: ["Convertible", "White", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-maybach-gls-600-white-and-black",
    name: "Mercedes-Maybach GLS 600 (White & Black)",
    make: "Mercedes-Maybach",
    model: "GLS 600 (White & Black)",
    category: "suv luxury",
    categoryLabel: "Ultra luxury SUV",
    price: 700,
    mileage: "100 miles/day",
    color: "White & Black",
    summary: "Mercedes-Maybach GLS 600 (White & Black) in White & Black added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-maybach-gls-600-white-and-black.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-maybach-gls-600-white-and-black/01.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-white-and-black/02.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-white-and-black/03.jpg"],
    tags: ["Ultra luxury SUV", "White & Black", "Pixieset import", "Rate to confirm"],
    details: ["Ultra luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-huracan-spyder",
    name: "Lamborghini Huracán Spyder",
    make: "Lamborghini",
    model: "Huracán Spyder",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 500,
    mileage: "100 miles/day",
    color: "",
    summary: "Lamborghini Huracán Spyder added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-huracan-spyder.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-huracan-spyder/01.jpg", "/assets/fleet-galleries/lamborghini-huracan-spyder/02.jpg", "/assets/fleet-galleries/lamborghini-huracan-spyder/03.jpg"],
    tags: ["Convertible", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lamborghini-mansory-urus",
    name: "Lamborghini Mansory Urus",
    make: "Lamborghini",
    model: "Mansory Urus",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 1100,
    mileage: "100 miles/day",
    color: "",
    summary: "Lamborghini Mansory Urus added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lamborghini-mansory-urus.jpg",
    gallery: ["/assets/fleet-galleries/lamborghini-mansory-urus/01.jpg", "/assets/fleet-galleries/lamborghini-mansory-urus/02.jpg", "/assets/fleet-galleries/lamborghini-mansory-urus/03.jpg"],
    tags: ["Super SUV", "Pixieset import", "Rate to confirm"],
    details: ["Super SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "bmw-m8-competition",
    name: "BMW M8 Competition",
    make: "BMW",
    model: "M8 Competition",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 350,
    mileage: "100 miles/day",
    color: "",
    summary: "BMW M8 Competition added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/bmw-m8-competition.jpg",
    gallery: ["/assets/fleet-galleries/bmw-m8-competition/01.jpg", "/assets/fleet-galleries/bmw-m8-competition/02.jpg", "/assets/fleet-galleries/bmw-m8-competition/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "lotus-emira",
    name: "Lotus Emira",
    make: "Lotus",
    model: "Emira",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 450,
    mileage: "100 miles/day",
    color: "",
    summary: "Lotus Emira added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/lotus-emira.jpg",
    gallery: ["/assets/fleet-galleries/lotus-emira/01.jpg", "/assets/fleet-galleries/lotus-emira/02.jpg", "/assets/fleet-galleries/lotus-emira/03.jpg"],
    tags: ["Supercar", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-maybach-gls-600-white",
    name: "Mercedes-Maybach GLS 600 (White)",
    make: "Mercedes-Maybach",
    model: "GLS 600 (White)",
    category: "suv luxury",
    categoryLabel: "Ultra luxury SUV",
    price: 700,
    mileage: "100 miles/day",
    color: "White",
    summary: "Mercedes-Maybach GLS 600 (White) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-maybach-gls-600-white.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-maybach-gls-600-white/01.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-white/02.jpg", "/assets/fleet-galleries/mercedes-maybach-gls-600-white/03.jpg"],
    tags: ["Ultra luxury SUV", "White", "Pixieset import", "Rate to confirm"],
    details: ["Ultra luxury SUV option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "mercedes-amg-gt-r-blue",
    name: "Mercedes-AMG GT R (Blue)",
    make: "Mercedes AMG",
    model: "GT R (Blue)",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 650,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "Mercedes-AMG GT R (Blue) in Blue added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/mercedes-amg-gt-r-blue.jpg",
    gallery: ["/assets/fleet-galleries/mercedes-amg-gt-r-blue/01.jpg", "/assets/fleet-galleries/mercedes-amg-gt-r-blue/02.jpg", "/assets/fleet-galleries/mercedes-amg-gt-r-blue/03.jpg"],
    tags: ["Supercar", "Blue", "Pixieset import", "Rate to confirm"],
    details: ["Supercar option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  {
    slug: "rolls-royce-dawn-convertible-white",
    name: "Rolls-Royce Dawn Convertible (white)",
    make: "Rolls-Royce",
    model: "Dawn Convertible (white)",
    category: "supercar convertible",
    categoryLabel: "Convertible",
    price: 1200,
    mileage: "100 miles/day",
    color: "White",
    summary: "Rolls-Royce Dawn Convertible (white) in White added to the KD's Exotics showroom for private rentals, events, and content-ready arrivals.",
    image: "/assets/fleet/rolls-royce-dawn-convertible-white.jpg",
    gallery: ["/assets/fleet-galleries/rolls-royce-dawn-convertible-white/01.jpg", "/assets/fleet-galleries/rolls-royce-dawn-convertible-white/02.jpg", "/assets/fleet-galleries/rolls-royce-dawn-convertible-white/03.jpg"],
    tags: ["Convertible", "White", "Pixieset import", "Rate to confirm"],
    details: ["Convertible option for private bookings", "Photo set imported from the DIGITLCARS fleet folder", "Availability, deposit, and delivery details confirmed before approval", "Final specs and rate can be adjusted inside the admin CRM"],
  },
  // End Pixieset fleet import - 2026-07-07
];

export function formatPrice(price) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatCategory(category) {
  const label = category.split(" ")[0];
  return label === "suv" ? "SUV" : label;
}

export function getVehicle(slug) {
  return fleet.find((car) => car.slug === slug);
}
