const gallery = (slug, count) =>
  Array.from({ length: count }, (_, index) => `/assets/fleet-galleries/${slug}/${String(index + 1).padStart(2, "0")}.jpg`);

export const fleet = [
  {
    slug: "2021-bmw-m3-comp",
    name: "2021 BMW M3 Comp",
    make: "BMW",
    model: "M3 Comp",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 250,
    mileage: "100 miles/day",
    color: "Blue exterior / Silverstone interior",
    summary: "A sharp, executive performance sedan with carbon exterior upgrades and a tuned exhaust note.",
    image: "/assets/fleet/2021-bmw-m3-comp.jpg?v=sharp-20260620",
    gallery: gallery("2021-bmw-m3-comp", 5),
    tags: ["Carbon exterior", "Silverstone interior", "$225.00 3-5 days", "$200.00 6-7 days"],
    details: ["Carbon exterior package", "Performance exhaust", "Four-door daily usability", "Great for OC, Irvine, Newport, and LA delivery"],
  },
  {
    slug: "2022-porsche-911-carrera",
    name: "2022 Porsche 911 Carrera",
    make: "Porsche",
    model: "911 Carrera",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 400,
    mileage: "100 miles/day",
    color: "Red",
    summary: "A clean red 911 with a carbon wing and upgraded exhaust for a refined but unmistakable arrival.",
    image: "/assets/fleet/2022-porsche-911-carrera.jpg",
    gallery: gallery("2022-porsche-911-carrera", 5),
    tags: ["Carbon wing", "Upgraded exhaust", "$350.00 3-5 days", "$325.00 6-7 days"],
    details: ["Iconic 911 silhouette", "Carbon wing", "Upgraded exhaust", "Ideal for dinners, coast drives, and weekend bookings"],
  },
  {
    slug: "2017-audi-r8",
    name: "2017 Audi R8",
    make: "Audi",
    model: "R8",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 500,
    mileage: "100 miles/day",
    color: "Matte black",
    summary: "A matte black R8 with carbon, exhaust, and tune work that brings supercar presence without shouting.",
    image: "/assets/fleet/2017-audi-r8.jpg?v=sharp-20260620",
    gallery: gallery("2017-audi-r8", 5),
    tags: ["Matte black", "Carbon", "Exhaust + tune", "$450.00 3-5 days"],
    details: ["Matte black finish", "Carbon accents", "Performance exhaust and tune", "Strong fit for nightlife, shoots, and Beverly Hills delivery"],
  },
  {
    slug: "2015-lamborghini-huracan-lp-610-4",
    name: "2015 Lamborghini Huracan LP-610-4",
    make: "Lamborghini",
    model: "Huracan LP-610-4",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "British Racing Green / red interior",
    summary: "A full-build Huracan with a 1016 kit, LAB Build upgrades, wheels, exhaust, tune, and carbon throughout.",
    image: "/assets/fleet/2015-lamborghini-huracan-lp-610-4.jpg",
    gallery: gallery("2015-lamborghini-huracan-lp-610-4", 5),
    tags: ["1016 kit", "LAB Build", "Carbon everywhere", "$750.00 3-5 days"],
    details: ["Full 1016 kit", "LAB Build upgrades", "Wheels, exhaust, and tune", "Red interior with major visual impact"],
  },
  {
    slug: "2022-lamborghini-huracan",
    name: "2022 Lamborghini Huracan",
    make: "Lamborghini",
    model: "Huracan",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 800,
    mileage: "100 miles/day",
    color: "Blue convertible",
    summary: "A blue Huracan convertible built for coastal drives, VIP entrances, and open-air supercar moments.",
    image: "/assets/fleet/2022-lamborghini-huracan.jpg",
    gallery: gallery("2022-lamborghini-huracan", 1),
    tags: ["Convertible", "Blue exterior", "$750.00 3-5 days", "$725.00 6-7 days"],
    details: ["Open-air Lamborghini experience", "Blue exterior", "Strong hero car for Malibu and Newport Beach", "More photos can be added when available"],
  },
  {
    slug: "2016-ferrari-488-gtb",
    name: "2016 Ferrari 488 GTB",
    make: "Ferrari",
    model: "488 GTB",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 750,
    mileage: "100 miles/day",
    color: "Red",
    summary: "A red Ferrari 488 GTB with exhaust presence and timeless exotic-car energy.",
    image: "/assets/fleet/2016-ferrari-488-gtb.jpg",
    gallery: gallery("2016-ferrari-488-gtb", 5),
    tags: ["Red Ferrari", "Exhaust", "$725.00 3-5 days", "$700.00 6-7 days"],
    details: ["Ferrari V8 presence", "Red exterior", "Exhaust upgrade", "Best for weddings, nightlife, content, and VIP arrivals"],
  },
  {
    slug: "2018-mclaren-570s-spider",
    name: "2018 McLaren 570s Spider",
    make: "McLaren",
    model: "570s Spider",
    category: "supercar",
    categoryLabel: "Supercar",
    price: 650,
    mileage: "100 miles/day",
    color: "Blue",
    summary: "A blue McLaren Spider with downpipes, exhaust, tune, and carbon details for a rawer supercar feel.",
    image: "/assets/fleet/2018-mclaren-570s-spider.jpg?v=sharp-20260620",
    gallery: gallery("2018-mclaren-570s-spider", 4),
    tags: ["Spider", "Downpipes", "Exhaust + tune", "$600.00 3-5 days"],
    details: ["Convertible Spider body", "Full downpipes", "Exhaust and tune", "Carbon details with dramatic door presentation"],
  },
  {
    slug: "2019-mercedes-g63-amg",
    name: "2019 Mercedes G63 AMG",
    make: "Mercedes",
    model: "G63 AMG",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 400,
    mileage: "100 miles/day",
    color: "Matte black / white interior",
    summary: "A VIP SUV booking option with matte black presence and a white interior specification.",
    image: "/assets/fleet/2022-mercedes-gle53-amg.jpg?v=sharp-20260620",
    gallery: gallery("2019-mercedes-g63-amg", 1),
    tags: ["Matte black", "White interior", "$350.00 3-5 days", "$325.00 6-7 days"],
    details: ["Luxury SUV profile", "Matte black look", "White interior", "Exact G63 photos can be swapped in when available"],
  },
  {
    slug: "2022-mercedes-gle53-amg",
    name: "2022 Mercedes GLE53 AMG",
    make: "Mercedes",
    model: "GLE53 AMG",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 300,
    mileage: "100 miles/day",
    color: "Matte black",
    summary: "A 100k-spec AMG SUV with massaging seats and a polished matte-black look.",
    image: "/assets/fleet/2022-mercedes-gle53-amg.jpg?v=sharp-20260620",
    gallery: gallery("2022-mercedes-gle53-amg", 5),
    tags: ["Matte black", "Massaging seats", "100k spec", "$250.00 3-5 days"],
    details: ["AMG SUV comfort", "Massaging seats", "100k-spec build", "Great for LAX/SNA delivery and executive transport"],
  },
  {
    slug: "2022-cadillac-escalade",
    name: "2022 Cadillac Escalade",
    make: "Cadillac",
    model: "Escalade",
    category: "suv luxury",
    categoryLabel: "Luxury SUV",
    price: 300,
    mileage: "100 miles/day",
    color: "Dark blue",
    summary: "A dark blue Escalade with captain's chairs for groups, events, airport delivery, and VIP comfort.",
    image: "/assets/fleet/2022-cadillac-escalade.jpg?v=sharp-20260620",
    gallery: gallery("2022-cadillac-escalade", 5),
    tags: ["Captain's chairs", "Dark blue", "$250.00 3-5 days", "$200.00 6-7 days"],
    details: ["Captain's chairs", "Luxury full-size SUV", "Ideal for groups and event logistics", "Comfortable for LAX/SNA arrivals"],
  },
  {
    slug: "2026-ford-f150-raptor",
    name: "2026 Ford F150 Raptor",
    make: "Ford",
    model: "F150 Raptor",
    category: "suv luxury",
    categoryLabel: "Performance truck",
    price: 250,
    mileage: "100 miles/day",
    color: "Shelter Green",
    summary: "A Shelter Green Raptor with leveling kit, wheels, and a high-spec truck presence.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2026-ford-f150-raptor", 1),
    tags: ["Shelter Green", "Level kit + wheels", "90k spec", "$200.00 3-5 days"],
    details: ["Level kit and wheels", "90k-spec truck", "Great for lifestyle shoots and statement arrivals", "Exact Raptor photos can be added when available"],
  },
  {
    slug: "2020-lamborghini-urus",
    name: "2020 Lamborghini Urus",
    make: "Lamborghini",
    model: "Urus",
    category: "suv luxury",
    categoryLabel: "Super SUV",
    price: 750,
    mileage: "100 miles/day",
    color: "Matte black / orange interior",
    summary: "A matte black Urus with orange interior and full turbo-back Akrapovic exhaust.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2020-lamborghini-urus", 1),
    tags: ["Matte black", "Orange interior", "Akrapovic exhaust", "$700.00 3-5 days"],
    details: ["Full turbo-back Akrapovic exhaust", "Orange interior", "Matte black look", "Exact Urus photos can be added when available"],
  },
  {
    slug: "2024-bmw-m4-comp",
    name: "2024 BMW M4-Comp",
    make: "BMW",
    model: "M4-Comp",
    category: "sports luxury",
    categoryLabel: "Sports luxury",
    price: 300,
    mileage: "100 miles/day",
    color: "Skyscraper gray / ivory white interior",
    summary: "A Skyscraper Gray M4 Comp with ivory white interior, RVNG exhaust, lowering springs, and spacers.",
    image: "/assets/fleet/2024-bmw-m4-comp.jpg",
    gallery: gallery("2024-bmw-m4-comp", 5),
    tags: ["RVNG exhaust", "Lowering springs", "Ivory interior", "$250.00 3-5 days"],
    details: ["RVNG exhaust", "Lowering springs and spacers", "Ivory white interior", "A strong coupe option for OC and LA bookings"],
  },
  {
    slug: "2026-chevy-c8-corvette",
    name: "2026 Chevy C8 Corvette",
    make: "Chevy",
    model: "C8 Corvette",
    category: "supercar",
    categoryLabel: "Sports car",
    price: 250,
    mileage: "100 miles/day",
    color: "Torch Red",
    summary: "A Torch Red C8 Corvette with exhaust and splitter for accessible mid-engine performance.",
    image: "/assets/kds-hero.png",
    gallery: gallery("2026-chevy-c8-corvette", 1),
    tags: ["Torch Red", "Exhaust", "Splitter", "$225.00 3-5 days"],
    details: ["Mid-engine Corvette platform", "Torch Red exterior", "Exhaust and splitter", "Exact C8 photos can be added when available"],
  },
];

export function formatPrice(price) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatCategory(category) {
  const label = category.split(" ")[0];
  return label === "suv" ? "SUV" : label;
}

export function getVehicle(slug) {
  return fleet.find((car) => car.slug === slug);
}
