import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "./supabase-config.js?v=fleet-sync-20260714";

const root = document.querySelector("[data-quotes-app]");
const navButton = document.querySelector('[data-crm-section="requests"]');
const newButton = document.querySelector("[data-new-quote]");
const supabase = window.prestigeLuxorSupabase || createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const OPEN = ["draft", "sent", "viewed", "follow_up", "accepted", "deposit_pending"];
const ACCEPTED = ["accepted", "deposit_pending"];
const LOST = ["declined", "expired", "cancelled"];
const STATUS_LABELS = { draft:"Draft", sent:"Sent", viewed:"Viewed", follow_up:"Follow-Up", accepted:"Accepted", deposit_pending:"Deposit Pending", converted:"Converted", declined:"Declined", expired:"Expired", cancelled:"Cancelled" };
const LINE_ITEM_TYPES = ["Delivery", "Pickup", "Additional mileage", "Chauffeur", "Late return", "Cleaning", "Fuel", "Airport fee", "Event / wedding fee", "Other"];
const COST_TYPES = ["Delivery cost", "Detail cost", "Sales commission", "Processing fee estimate", "Other cost"];

let model = { quotes:[], customers:[], leads:[], cars:[], partners:[], employees:[], reservations:[], blocks:[], role:"staff" };
let loaded = false;
let selected = null;
let detailEvents = [];
let detailRevisions = [];
let filter = { scope:"all", search:"", status:"all", vehicle:"all", employee:"all", source:"all", created:"", rental:"" };
let builder = { quote:null, draft:{}, step:0, lineItems:[], costs:[] };

const escapeHtml = (value) => String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money = (value) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value||0));
const shortMoney = (value) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(value||0));
const dateLabel = (value, withTime=false) => value ? new Date(value).toLocaleString("en-US", withTime ? {month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"} : {month:"short",day:"numeric",year:"numeric"}) : "—";
const fullName = (item) => [item?.customer_first_name ?? item?.first_name, item?.customer_last_name ?? item?.last_name].filter(Boolean).join(" ").trim();
const employeeName = (id) => model.employees.find((item)=>String(item.user_id)===String(id))?.display_name || "Unassigned";
const partnerFor = (id) => model.partners.find((item)=>String(item.car_id)===String(id));
const localInput = (value) => { if(!value)return ""; const d=new Date(value); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16); };
const toIso = (value) => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toISOString() : null;
const uid = () => crypto.randomUUID();

function toast(message, tone="success") {
  let node = document.querySelector("[data-quote-toast]");
  if (!node) { node=document.createElement("div"); node.dataset.quoteToast=""; node.className="quote-toast"; node.setAttribute("role","status"); document.body.append(node); }
  node.textContent=message; node.dataset.tone=tone; node.classList.add("show");
  window.clearTimeout(toast.timer); toast.timer=window.setTimeout(()=>node.classList.remove("show"),4200);
}

async function token(){const {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Sign in again to use quotes.");return data.session.access_token;}
async function api(path="quotes",options={}){const response=await fetch(`/api/${path}`,{...options,headers:{Authorization:`Bearer ${await token()}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const message=data.error||"Quote request failed.";if(/quotes|crm_customers|quote_events/i.test(message)&&/schema|table|not found|cache/i.test(message))throw new Error("The new quote database is not installed yet. Run supabase/quotes-v2.sql in Supabase SQL Editor, then refresh the CRM.");throw new Error(message);}return data;}

function statusBadge(status){return `<span class="quote-v2-status ${escapeHtml(status)}">${escapeHtml(STATUS_LABELS[status]||status)}</span>`;}
function quoteScope(quote){if(filter.scope==="open")return OPEN.includes(quote.status);if(filter.scope==="accepted")return ACCEPTED.includes(quote.status);if(filter.scope==="converted")return quote.status==="converted";if(filter.scope==="lost")return LOST.includes(quote.status);return true;}
function visibleQuotes(){const search=filter.search.toLowerCase();return model.quotes.filter((quote)=>quoteScope(quote)&&(!search||[quote.quote_number,fullName(quote),quote.customer_phone,quote.customer_email,quote.vehicle_name].some((value)=>String(value||"").toLowerCase().includes(search)))&&(filter.status==="all"||quote.status===filter.status)&&(filter.vehicle==="all"||String(quote.vehicle_id)===filter.vehicle)&&(filter.employee==="all"||String(quote.assigned_user_id||"")===filter.employee)&&(filter.source==="all"||String(quote.lead_source||"")===filter.source)&&(!filter.created||String(quote.created_at||"").slice(0,10)===filter.created)&&(!filter.rental||String(quote.start_at||"").slice(0,10)===filter.rental));}

function renderKpis(){const open=model.quotes.filter((q)=>OPEN.includes(q.status));const sent=model.quotes.filter((q)=>q.sent_at);const converted=model.quotes.filter((q)=>q.status==="converted");const soon=Date.now()+48*3600000;return `<div class="quote-v2-kpis"><article><span>Open Quotes</span><strong>${open.length}</strong></article><article><span>Quote Value</span><strong>${shortMoney(open.reduce((s,q)=>s+Number(q.rental_total||0),0))}</strong></article><article><span>Accepted</span><strong>${model.quotes.filter((q)=>ACCEPTED.includes(q.status)).length}</strong></article><article><span>Conversion Rate</span><strong>${sent.length?Math.round(converted.length/sent.length*100):0}%</strong></article><article><span>Expiring Soon</span><strong>${open.filter((q)=>q.expires_at&&new Date(q.expires_at).getTime()<=soon&&new Date(q.expires_at)>new Date()).length}</strong></article></div>`;}

function renderList(){
  selected=null; const quotes=visibleQuotes(); const sources=[...new Set(model.quotes.map((q)=>q.lead_source).filter(Boolean))].sort();
  root.innerHTML=`${renderKpis()}
    <section class="quote-v2-list-card">
      <div class="quote-scope-tabs" role="tablist" aria-label="Quote views">${[["all","All"],["open","Open"],["accepted","Accepted"],["converted","Converted"],["lost","Lost"]].map(([value,label])=>`<button class="${filter.scope===value?"active":""}" type="button" data-quote-scope="${value}">${label}</button>`).join("")}</div>
      <div class="quote-v2-toolbar"><label class="quote-v2-search"><span>Search quotes</span><input type="search" value="${escapeHtml(filter.search)}" placeholder="Customer, phone, quote #, or vehicle" data-quote-search></label><label><span>Status</span><select data-quote-filter="status"><option value="all">All statuses</option>${Object.entries(STATUS_LABELS).map(([value,label])=>`<option value="${value}" ${filter.status===value?"selected":""}>${label}</option>`).join("")}</select></label><details class="quote-more-filters"><summary>More filters</summary><div><label><span>Vehicle</span><select data-quote-filter="vehicle"><option value="all">All vehicles</option>${model.cars.map((c)=>`<option value="${c.id}" ${filter.vehicle===c.id?"selected":""}>${escapeHtml(c.name)}</option>`).join("")}</select></label><label><span>Assigned to</span><select data-quote-filter="employee"><option value="all">All employees</option><option value="" ${filter.employee===""?"selected":""}>Unassigned</option>${model.employees.map((e)=>`<option value="${e.user_id}" ${filter.employee===e.user_id?"selected":""}>${escapeHtml(e.display_name||e.role)}</option>`).join("")}</select></label><label><span>Lead source</span><select data-quote-filter="source"><option value="all">All sources</option>${sources.map((s)=>`<option value="${escapeHtml(s)}" ${filter.source===s?"selected":""}>${escapeHtml(s)}</option>`).join("")}</select></label><label><span>Created date</span><input type="date" value="${filter.created}" data-quote-filter="created"></label><label><span>Rental date</span><input type="date" value="${filter.rental}" data-quote-filter="rental"></label></div></details></div>
      ${quotes.length?`<div class="crm-table-container quote-v2-table"><table><thead><tr><th>Quote #</th><th>Customer</th><th>Vehicle</th><th>Rental Dates</th><th>Quote Total</th><th>Deposit Required</th><th>Created</th><th>Expiration</th><th>Assigned To</th><th>Status</th><th>Actions</th></tr></thead><tbody>${quotes.map((quote)=>`<tr data-open-quote="${quote.id}" tabindex="0"><td><strong>${escapeHtml(quote.quote_number)}</strong></td><td><strong>${escapeHtml(fullName(quote))}</strong><small>${escapeHtml(quote.customer_phone||quote.customer_email||"")}</small></td><td>${escapeHtml(quote.vehicle_name)}</td><td>${dateLabel(quote.start_at)}<small>${dateLabel(quote.end_at)}</small></td><td><strong>${money(quote.rental_total)}</strong></td><td>${money(quote.amount_required)}</td><td>${dateLabel(quote.created_at)}</td><td>${dateLabel(quote.expires_at,true)}</td><td>${escapeHtml(employeeName(quote.assigned_user_id))}</td><td>${statusBadge(quote.status)}</td><td><button class="quote-row-action" type="button" data-open-quote-button="${quote.id}">Open</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="quote-v2-empty"><strong>No quotes yet</strong><p>Create your first quote and start converting inquiries into bookings.</p><button class="primary-button" type="button" data-empty-new-quote>Create Quote</button></div>`}
    </section>`;
}

function timeline(events){const important=["created","sent","resent","viewed","accepted","payment_requested","deposit_paid","converted","declined","cancelled","expired","updated"];return `<ol class="quote-timeline">${events.filter((e)=>important.includes(e.event_type)).map((e)=>`<li><i></i><div><strong>${escapeHtml(e.event_type.replaceAll("_"," "))}</strong><span>${escapeHtml(e.detail||"")}</span><time>${dateLabel(e.created_at,true)}</time></div></li>`).join("")||`<li><i></i><div><strong>Quote created</strong></div></li>`}</ol>`;}

function contextualActions(q){const actions=[];if(!["converted","cancelled","expired"].includes(q.status))actions.push(`<button class="secondary-button compact" data-detail-action="edit">Edit Quote</button>`);if(q.status==="draft")actions.push(`<button class="primary-button compact" data-detail-action="send">Send Quote</button>`);if(["sent","viewed","follow_up","accepted","deposit_pending"].includes(q.status))actions.push(`<button class="secondary-button compact" data-detail-action="send">Resend</button>`);actions.push(`<button class="secondary-button compact" data-detail-action="copy">Copy Link</button>`);actions.push(`<button class="secondary-button compact" data-detail-action="duplicate">Duplicate</button>`);if(["sent","viewed","follow_up"].includes(q.status))actions.push(`<button class="secondary-button compact" data-detail-action="accept">Mark Accepted</button><button class="secondary-button compact" data-detail-action="decline">Mark Declined</button>`);if(q.accepted_at&&Number(q.amount_required)>Number(q.deposit_paid_amount))actions.push(`<button class="secondary-button compact" data-detail-action="payment">Record Reservation Payment</button>`);if(q.accepted_at&&Number(q.amount_required)<=Number(q.deposit_paid_amount)&&q.status!=="converted")actions.push(`<button class="primary-button compact" data-detail-action="convert">Convert to Reservation</button>`);if(q.status==="draft")actions.push(`<button class="danger-button compact" data-detail-action="delete">Delete Draft</button>`);else if(!["converted","cancelled"].includes(q.status))actions.push(`<button class="danger-button compact" data-detail-action="cancel">Cancel Quote</button>`);return actions.join("");}

async function openDetail(id){const cached=model.quotes.find(quote=>String(quote.id)===String(id));if(cached){selected=cached;detailEvents=[];detailRevisions=[];renderDetail();}else root.innerHTML=`<div class="crm-loading-state quotes-loading">Loading quote…</div>`;try{const data=await api(`quotes?id=${encodeURIComponent(id)}`);if(selected&&String(selected.id)!==String(id))return;selected=data.quote;detailEvents=data.events||[];detailRevisions=data.revisions||[];renderDetail();}catch(error){if(cached)return;root.innerHTML=`<div class="quote-v2-error"><strong>Quote could not be opened</strong><p>${escapeHtml(error.message)}</p><button class="secondary-button" data-back-quotes>Back to quotes</button></div>`;}}

function renderDetail(){const q=selected;const lineItems=(q.line_items||[]).map((i)=>`<p><span>${escapeHtml(i.description)} <small>${i.quantity} × ${money(i.rate)}</small></span><strong>${money(i.amount)}</strong></p>`).join("");const costs=(q.internal_costs||[]).map((i)=>`<p><span>${escapeHtml(i.description)}</span><strong>-${money(i.amount)}</strong></p>`).join("");root.innerHTML=`<div class="quote-detail-nav"><button type="button" class="quote-back-button" data-back-quotes>← All quotes</button><div>${contextualActions(q)}</div></div>
    <section class="quote-v2-detail-head"><div><p class="eyebrow">${escapeHtml(q.quote_number)}</p><h3>${escapeHtml(fullName(q))}</h3><span>${escapeHtml(q.vehicle_name)} · ${dateLabel(q.start_at,true)} – ${dateLabel(q.end_at,true)}</span></div><div><strong>${money(q.rental_total)}</strong>${statusBadge(q.status)}</div></section>
    <div class="quote-detail-grid-v2"><main>
      <section class="quote-detail-card"><header><h4>Quote summary</h4><span>Revision ${q.revision}</span></header><div class="quote-money-lines"><p><span>Rental · ${q.duration_value} ${escapeHtml(q.duration_type)}</span><strong>${money((q.rate_type==="flat"?q.rate_amount:q.rate_amount*q.duration_value))}</strong></p>${lineItems}<p><span>Subtotal</span><strong>${money(q.subtotal)}</strong></p>${Number(q.discount_amount)?`<p class="deduction"><span>${escapeHtml(q.discount_label)}</span><strong>-${money(q.discount_amount)}</strong></p>`:""}${Number(q.tax_amount)?`<p><span>Tax</span><strong>${money(q.tax_amount)}</strong></p>`:""}<p class="total"><span>Rental Total</span><strong>${money(q.rental_total)}</strong></p><p><span>Amount Required to Reserve</span><strong>${money(q.amount_required)}</strong></p><p><span>Reservation Payment Received</span><strong>${money(q.deposit_paid_amount)}</strong></p><p><span>Remaining Rental Balance</span><strong>${money(q.remaining_balance)}</strong></p><p class="security"><span>Refundable Security Deposit <small>Not rental revenue</small></span><strong>${money(q.security_deposit)}</strong></p></div></section>
      <section class="quote-detail-card"><header><h4>Customer & rental</h4></header><dl class="quote-detail-facts"><div><dt>Customer</dt><dd>${escapeHtml(fullName(q))}</dd></div><div><dt>Phone</dt><dd>${escapeHtml(q.customer_phone||"—")}</dd></div><div><dt>Email</dt><dd>${escapeHtml(q.customer_email||"—")}</dd></div><div><dt>Vehicle</dt><dd>${escapeHtml(q.vehicle_name)}</dd></div><div><dt>Ownership</dt><dd>${q.ownership_type==="partner"?"Partner Vehicle":"Prestige Owned"}</dd></div><div><dt>Rental dates</dt><dd>${dateLabel(q.start_at,true)} – ${dateLabel(q.end_at,true)}</dd></div><div><dt>Assigned to</dt><dd>${escapeHtml(employeeName(q.assigned_user_id))}</dd></div><div><dt>Lead source</dt><dd>${escapeHtml(q.lead_source||"—")}</dd></div><div><dt>Created</dt><dd>${dateLabel(q.created_at,true)}</dd></div><div><dt>Valid until</dt><dd>${dateLabel(q.expires_at,true)}</dd></div></dl></section>
      ${q.customer_message?`<section class="quote-detail-card"><header><h4>Customer message</h4></header><p class="quote-note-copy">${escapeHtml(q.customer_message)}</p></section>`:""}
      ${q.internal_notes?`<section class="quote-detail-card internal"><header><h4>Internal notes</h4><span>Staff only</span></header><p class="quote-note-copy">${escapeHtml(q.internal_notes)}</p></section>`:""}
    </main><aside>
      <section class="quote-detail-card profit"><header><h4>Expected profit</h4><span>Staff only</span></header><div class="quote-money-lines"><p><span>Quote revenue</span><strong>${money(q.rental_total)}</strong></p>${Number(q.partner_cost)?`<p class="deduction"><span>Partner cost</span><strong>-${money(q.partner_cost)}</strong></p>`:""}${costs}<p class="total"><span>Expected Profit</span><strong>${money(q.expected_profit)}</strong></p></div></section>
      <section class="quote-detail-card"><header><h4>Next follow-up</h4></header><div class="quote-followup-control"><select data-followup-choice><option value="later">Later today</option><option value="tomorrow">Tomorrow</option><option value="two_days">2 days</option><option value="custom">Custom</option></select><input type="datetime-local" data-followup-custom hidden><button class="secondary-button compact" data-save-followup>Schedule</button></div>${q.follow_up_at?`<p class="quote-followup-due">Due ${dateLabel(q.follow_up_at,true)}</p>`:""}</section>
      <section class="quote-detail-card"><header><h4>Status timeline</h4></header>${timeline(detailEvents)}</section>
      ${detailRevisions.length?`<section class="quote-detail-card"><header><h4>Revision history</h4></header>${detailRevisions.map((r)=>`<p class="quote-revision-row"><span>V${r.revision} · ${dateLabel(r.created_at,true)}</span><strong>${money(r.rental_total)}</strong></p>`).join("")}</section>`:""}
      ${q.reservation_id?`<section class="quote-detail-card linked"><header><h4>Linked rental</h4></header><button class="primary-button compact" data-open-reservation="${q.reservation_id}">Open Reservation / Agreement</button>${q.invoice_id?`<button class="secondary-button compact" data-open-quote-invoice="${q.invoice_id}">Open Invoice</button>`:""}</section>`:""}
    </aside></div>`;}

function ensureDialogs(){if(document.querySelector("[data-quote-builder-dialog]"))return;document.body.insertAdjacentHTML("beforeend",`<dialog class="quote-builder-dialog" data-quote-builder-dialog><form class="quote-builder" data-quote-builder-form novalidate><header class="quote-builder-head"><div><p class="eyebrow">Fast quote builder</p><h2 data-builder-title>New Quote</h2><p>Customer, rental, pricing, then send.</p></div><button class="booking-dialog-close" type="button" data-close-builder aria-label="Close quote builder">×</button></header><nav class="quote-builder-steps" aria-label="Quote steps">${["Customer","Rental","Pricing","Review"].map((label,i)=>`<button type="button" data-builder-step-button="${i}"><b>${i+1}</b><span>${label}</span></button>`).join("")}</nav><div class="quote-builder-layout"><div class="quote-builder-fields" data-builder-fields></div><aside class="quote-live-summary" data-quote-summary></aside></div><footer class="quote-builder-footer"><p class="admin-status" role="status" data-builder-status></p><button class="secondary-button" type="button" data-builder-back>Back</button><button class="secondary-button" type="button" data-save-draft>Save Draft</button><button class="primary-button" type="button" data-builder-next>Continue</button><button class="primary-button" type="button" data-save-send hidden>Save &amp; Send Quote</button></footer></form></dialog><dialog class="quote-action-dialog" data-decline-dialog><form><header><h3>Mark quote declined</h3><button type="button" data-close-decline aria-label="Close">×</button></header><label>Reason<select name="reason">${["Price","Vehicle unavailable","Customer stopped responding","Chose competitor","Dates changed","Insurance issue","Age requirement","Deposit requirement","Other"].map(v=>`<option>${v}</option>`).join("")}</select></label><footer><button class="secondary-button" type="button" data-close-decline>Cancel</button><button class="danger-button" type="submit">Mark Declined</button></footer></form></dialog><dialog class="quote-action-dialog" data-payment-dialog><form><header><h3>Record reservation payment</h3><button type="button" data-close-payment aria-label="Close">×</button></header><label>Amount received<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Method<select name="method"><option>Stripe</option><option>Cash</option><option>Zelle</option><option>Wire</option><option>Other</option></select></label><label>Reference<input name="reference" placeholder="Receipt or payment ID"></label><footer><button class="secondary-button" type="button" data-close-payment>Cancel</button><button class="primary-button" type="submit">Record Payment</button></footer></form></dialog>`);bindDialogEvents();}

function customerStep(q){const labels=model.customers.map((c)=>`${fullName(c)} · ${c.phone||c.email}`);return `<section class="quote-builder-step"><div class="quote-step-title"><b>1</b><div><h3>Customer</h3><p>Select an existing customer, start from a lead, or add someone new.</p></div></div><div class="quote-form-grid"><label class="wide">Start from lead (optional)<select name="lead_id" data-builder-lead><option value="">No lead selected</option>${model.leads.map((l)=>`<option value="${l.id}" ${q?.lead_id===l.id?"selected":""}>${escapeHtml(l.name)} · ${escapeHtml(l.vehicle)} · ${dateLabel(l.created_at)}</option>`).join("")}</select></label><label class="wide">Select existing customer<input name="customer_search" list="quote-customer-list" placeholder="Search name, phone, or email" value="${q?.customer_id?escapeHtml(labels[model.customers.findIndex(c=>c.id===q.customer_id)]||""):""}" data-customer-search><datalist id="quote-customer-list">${labels.map(l=>`<option value="${escapeHtml(l)}"></option>`).join("")}</datalist><input type="hidden" name="customer_id" value="${q?.customer_id||""}"></label><label>First name<input name="customer_first_name" autocomplete="given-name" value="${escapeHtml(q?.customer_first_name||"")}"></label><label>Last name<input name="customer_last_name" autocomplete="family-name" value="${escapeHtml(q?.customer_last_name||"")}"></label><label>Phone<input name="customer_phone" type="tel" autocomplete="tel" value="${escapeHtml(q?.customer_phone||"")}"></label><label>Email<input name="customer_email" type="email" autocomplete="email" value="${escapeHtml(q?.customer_email||"")}"></label><label>Company <small>Optional</small><input name="customer_company" autocomplete="organization" value="${escapeHtml(q?.customer_company||"")}"></label><label>Lead source <small>Optional</small><input name="lead_source" placeholder="Google, referral, Instagram…" value="${escapeHtml(q?.lead_source||"")}"></label><label class="wide">Customer notes <small>Optional</small><textarea name="customer_notes" rows="3">${escapeHtml(q?.customer_notes||"")}</textarea></label></div></section>`;}

function defaultDates(){const start=new Date();start.setDate(start.getDate()+1);start.setHours(10,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return{start:localInput(start),end:localInput(end)};}
function rentalStep(q){const dates=defaultDates();return `<section class="quote-builder-step"><div class="quote-step-title"><b>2</b><div><h3>Rental details</h3><p>Choose the fleet vehicle and exact rental window.</p></div></div><div class="quote-form-grid"><label class="wide">Vehicle<select name="vehicle_id" data-builder-vehicle><option value="">Select a vehicle</option>${model.cars.map((c)=>`<option value="${c.id}" ${q?.vehicle_id===c.id?"selected":""}>${escapeHtml(c.name)} · ${shortMoney(c.price)}/day</option>`).join("")}</select></label><div class="quote-vehicle-preview wide" data-vehicle-preview></div><label>Start date &amp; time<input name="start_at" type="datetime-local" value="${localInput(q?.start_at)||dates.start}"></label><label>End date &amp; time<input name="end_at" type="datetime-local" value="${localInput(q?.end_at)||dates.end}"></label><div class="quote-availability wide" data-quote-availability></div></div></section>`;}

function pricingStep(q){return `<section class="quote-builder-step"><div class="quote-step-title"><b>3</b><div><h3>Pricing</h3><p>Build the customer-visible rental total and keep deposits separate.</p></div></div><div class="quote-form-grid"><label>Rate type<select name="rate_type"><option value="daily" ${q?.rate_type==="daily"?"selected":""}>Daily rate</option><option value="hourly" ${q?.rate_type==="hourly"?"selected":""}>Hourly rate</option><option value="flat" ${q?.rate_type==="flat"?"selected":""}>Flat rental amount</option><option value="custom" ${q?.rate_type==="custom"?"selected":""}>Custom rate × duration</option></select></label><label>Rental rate<input name="rate_amount" type="number" min="0" step="0.01" value="${q?.rate_amount||0}"></label><label class="quote-check"><input name="rental_taxable" type="checkbox" ${q?.rental_taxable?"checked":""}><span>Rental rate is taxable</span></label><div class="wide quote-line-builder"><header><div><h4>Additional charges</h4><p>Delivery, mileage, wedding packages, and custom line items.</p></div><button class="secondary-button compact" type="button" data-add-line>Add line item</button></header><div data-line-items></div></div><label>Discount type<select name="discount_type"><option value="fixed" ${q?.discount_type!=="percentage"?"selected":""}>Fixed amount</option><option value="percentage" ${q?.discount_type==="percentage"?"selected":""}>Percentage</option></select></label><label>Discount value<input name="discount_value" type="number" min="0" step="0.01" value="${q?.discount_value||0}"></label><label class="wide">Discount label<input name="discount_label" value="${escapeHtml(q?.discount_label||"VIP Discount")}"></label><label class="quote-check"><input name="tax_enabled" type="checkbox" ${q?.tax_enabled?"checked":""}><span>Apply tax</span></label><label>Tax rate %<input name="tax_rate" type="number" min="0" step="0.001" value="${q?.tax_rate||0}" ${q?.tax_enabled?"":"disabled"}></label><label>Amount required type<select name="amount_required_type"><option value="fixed" ${q?.amount_required_type!=="percentage"?"selected":""}>Fixed amount</option><option value="percentage" ${q?.amount_required_type==="percentage"?"selected":""}>Percentage of rental total</option></select></label><label>Amount required to reserve<input name="amount_required_value" type="number" min="0" step="0.01" value="${q?.amount_required_value||0}"></label><label class="wide security-field">Refundable Security Deposit <small>Separate from rental revenue</small><input name="security_deposit" type="number" min="0" step="0.01" value="${q?.security_deposit||0}"></label></div></section>`;}

function reviewStep(q){return `<section class="quote-builder-step"><div class="quote-step-title"><b>4</b><div><h3>Review &amp; send</h3><p>Add internal profitability, expiration, and the customer message.</p></div></div><div class="quote-form-grid"><label>Partner cost <small>Staff only</small><input name="partner_cost" type="number" min="0" step="0.01" value="${q?.partner_cost||0}"></label><label>Assigned employee<select name="assigned_user_id"><option value="">Unassigned</option>${model.employees.map((e)=>`<option value="${e.user_id}" ${q?.assigned_user_id===e.user_id?"selected":""}>${escapeHtml(e.display_name||e.role)}</option>`).join("")}</select></label><div class="wide quote-line-builder internal"><header><div><h4>Internal costs</h4><p>Never shown to the customer.</p></div><button class="secondary-button compact" type="button" data-add-cost>Add cost</button></header><div data-internal-costs></div></div><label>Expiration<select name="expiration_choice" data-expiration-choice><option value="24">24 Hours</option><option value="48" selected>48 Hours</option><option value="72">72 Hours</option><option value="custom">Custom</option></select></label><label>Valid until<input name="expires_at" type="datetime-local" value="${localInput(q?.expires_at)}" data-expiration-custom></label><label>Next follow-up<select name="follow_up_choice"><option value="">No reminder</option><option value="later">Later today</option><option value="tomorrow">Tomorrow</option><option value="two_days">2 days</option><option value="custom">Custom</option></select></label><label>Custom follow-up<input name="follow_up_at" type="datetime-local" value="${localInput(q?.follow_up_at)}"></label><label class="wide">Internal notes <small>Staff only</small><textarea name="internal_notes" rows="4" placeholder="Partner confirmation, discount discussion, follow-up context…">${escapeHtml(q?.internal_notes||"")}</textarea></label><label class="wide">Message to customer<textarea name="customer_message" rows="5">${escapeHtml(q?.customer_message||"Thank you for choosing Prestige Luxor. This quote is valid for 48 hours and vehicle availability is not guaranteed until your reservation payment is received.")}</textarea></label></div></section>`;}

function renderBuilderStep(){const fields=document.querySelector("[data-builder-fields]");if(!fields)return;const q={...(builder.quote||{}),...(builder.draft||{})};fields.innerHTML=[customerStep,rentalStep,pricingStep,reviewStep][builder.step](q);document.querySelectorAll("[data-builder-step-button]").forEach((b,i)=>{b.classList.toggle("active",i===builder.step);b.classList.toggle("done",i<builder.step);});document.querySelector("[data-builder-back]").hidden=builder.step===0;document.querySelector("[data-builder-next]").hidden=builder.step===3;document.querySelector("[data-save-send]").hidden=builder.step!==3;bindStepEvents();renderLineItems();renderCosts();updateBuilder();}

function quoteForm(){return document.querySelector("[data-quote-builder-form]");}
function value(name){const field=quoteForm()?.elements[name];return field?field.value:(builder.draft?.[name]??builder.quote?.[name]??"");}
function number(name){return Math.max(Number(value(name)||0),0);}
function checked(name){const field=quoteForm()?.elements[name];return field?Boolean(field.checked):Boolean(builder.draft?.[name]??builder.quote?.[name]);}
function captureBuilderStep(){const form=quoteForm();if(!form)return;const data=new FormData(form);for(const[key,val]of data.entries())builder.draft[key]=val;for(const name of ["rental_taxable","tax_enabled"]){if(form.elements[name])builder.draft[name]=Boolean(form.elements[name].checked);}builder.draft.line_items=builder.lineItems;builder.draft.internal_costs=builder.costs;}
function duration(){const start=new Date(value("start_at")).getTime(),end=new Date(value("end_at")).getTime(),type=value("rate_type");if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return 1;if(type==="hourly")return Math.max(Math.ceil((end-start)/3600000),1);if(type==="daily")return Math.max(Math.ceil((end-start)/86400000),1);return 1;}
function clientTotals(){const rateType=value("rate_type")||builder.quote?.rate_type||"daily",rate=number("rate_amount")||Number(builder.quote?.rate_amount||0),d=duration(),base=rateType==="flat"?rate:rate*d,lineTotal=builder.lineItems.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.rate||0),0),subtotal=base+lineTotal,discountType=value("discount_type")||builder.quote?.discount_type||"fixed",discountValue=number("discount_value")||Number(builder.quote?.discount_value||0),discount=discountType==="percentage"?subtotal*Math.min(discountValue,100)/100:Math.min(discountValue,subtotal),net=subtotal-discount,taxable=(checked("rental_taxable")?base:0)+builder.lineItems.filter(i=>i.taxable).reduce((s,i)=>s+Number(i.quantity||0)*Number(i.rate||0),0),tax=checked("tax_enabled")?(subtotal?taxable*(net/subtotal):0)*number("tax_rate")/100:0,total=net+tax,reqType=value("amount_required_type")||builder.quote?.amount_required_type||"fixed",reqValue=number("amount_required_value")||Number(builder.quote?.amount_required_value||0),required=Math.min(reqType==="percentage"?total*Math.min(reqValue,100)/100:reqValue,total),security=number("security_deposit")||Number(builder.quote?.security_deposit||0),partner=number("partner_cost")||Number(builder.quote?.partner_cost||0),costs=partner+builder.costs.reduce((s,i)=>s+Number(i.amount||0),0);return{rateType,rate,d,base,lineTotal,subtotal,discount,tax,total,required,remaining:Math.max(total-Number(builder.quote?.deposit_paid_amount||0),0),security,costs,profit:total-costs};}
function updateBuilder(){const summary=document.querySelector("[data-quote-summary]");if(!summary)return;const t=clientTotals(),car=model.cars.find(c=>c.id===value("vehicle_id"))||model.cars.find(c=>c.id===builder.quote?.vehicle_id);summary.innerHTML=`${car?.image_url?`<img src="${escapeHtml(car.image_url)}" alt="${escapeHtml(car.name)}" width="420" height="240">`:""}<p class="eyebrow">Live quote summary</p><h3>${escapeHtml(car?.name||"Select a vehicle")}</h3><span>${value("start_at")?dateLabel(toIso(value("start_at"))):"Rental dates"} · ${t.d} ${t.rateType==="hourly"?"hours":"days"}</span><div class="quote-summary-lines"><p><span>Rental</span><strong>${money(t.base)}</strong></p>${builder.lineItems.map(i=>`<p><span>${escapeHtml(i.description)}</span><strong>${money(Number(i.quantity||0)*Number(i.rate||0))}</strong></p>`).join("")}<p><span>Subtotal</span><strong>${money(t.subtotal)}</strong></p>${t.discount?`<p class="deduction"><span>Discount</span><strong>-${money(t.discount)}</strong></p>`:""}${t.tax?`<p><span>Tax</span><strong>${money(t.tax)}</strong></p>`:""}<p class="total"><span>Rental Total</span><strong>${money(t.total)}</strong></p><p><span>Required to Reserve</span><strong>${money(t.required)}</strong></p><p><span>Remaining Rental Balance</span><strong>${money(t.remaining)}</strong></p><p class="security"><span>Refundable Security Deposit</span><strong>${money(t.security)}</strong></p><p class="profit"><span>Expected Profit <small>Staff only</small></span><strong>${money(t.profit)}</strong></p></div>`;if(builder.step===1){renderVehiclePreview();checkAvailability();}}

function renderLineItems(){const node=document.querySelector("[data-line-items]");if(!node)return;node.innerHTML=builder.lineItems.length?builder.lineItems.map((item,i)=>`<div class="quote-line-row" data-line-index="${i}"><select data-line-field="description">${LINE_ITEM_TYPES.map(t=>`<option ${item.description===t?"selected":""}>${t}</option>`).join("")}</select><input data-line-field="quantity" aria-label="Quantity" type="number" min="0.01" step="0.01" value="${item.quantity}"><input data-line-field="rate" aria-label="Rate" type="number" min="0" step="0.01" value="${item.rate}"><label class="quote-mini-check"><input data-line-field="taxable" type="checkbox" ${item.taxable?"checked":""}>Tax</label><strong>${money(Number(item.quantity)*Number(item.rate))}</strong><button type="button" data-remove-line="${i}" aria-label="Remove line item">×</button></div>`).join(""):`<p class="quote-builder-empty">No additional charges.</p>`;}
function renderCosts(){const node=document.querySelector("[data-internal-costs]");if(!node)return;node.innerHTML=builder.costs.length?builder.costs.map((item,i)=>`<div class="quote-cost-row" data-cost-index="${i}"><select data-cost-field="description">${COST_TYPES.map(t=>`<option ${item.description===t?"selected":""}>${t}</option>`).join("")}</select><input data-cost-field="amount" aria-label="Cost amount" type="number" min="0" step="0.01" value="${item.amount}"><strong>${money(item.amount)}</strong><button type="button" data-remove-cost="${i}" aria-label="Remove cost">×</button></div>`).join(""):`<p class="quote-builder-empty">No internal costs.</p>`;}
function renderVehiclePreview(){const node=document.querySelector("[data-vehicle-preview]"),car=model.cars.find(c=>c.id===value("vehicle_id"));if(!node)return;node.innerHTML=car?`${car.image_url?`<img src="${escapeHtml(car.image_url)}" alt="${escapeHtml(car.name)}" width="280" height="170">`:""}<div><strong>${escapeHtml(car.name)}</strong><span>${escapeHtml(car.make)} · ${escapeHtml(car.model)}</span><small>${partnerFor(car.id)?.partner_name?`Partner Vehicle · ${escapeHtml(partnerFor(car.id).partner_name)}`:"Prestige Owned"} · ${shortMoney(car.price)}/day</small></div>`:`<span>Select a vehicle to see its details and availability.</span>`;}
function checkAvailability(){const node=document.querySelector("[data-quote-availability]"),carId=value("vehicle_id"),start=toIso(value("start_at")),end=toIso(value("end_at"));if(!node)return;if(!carId||!start||!end){node.className="quote-availability";node.textContent="Choose a vehicle and rental window to check availability.";return;}const conflict=model.reservations.find(r=>String(r.vehicle_id)===String(carId)&&String(r.id)!==String(builder.quote?.reservation_id||"")&&new Date(r.rental_start_at||`${r.rental_start}T00:00:00`)<new Date(end)&&new Date(r.rental_end_at||`${r.rental_end}T23:59:59`)>new Date(start));const block=model.blocks.find(b=>String(b.car_id)===String(carId)&&new Date(b.start_at)<new Date(end)&&new Date(b.end_at)>new Date(start));node.className=`quote-availability ${conflict||block?"conflict":"available"}`;node.textContent=conflict?`Conflict: ${conflict.agreement_number} overlaps this rental window.`:block?`Unavailable: ${block.reason||String(block.block_type).replaceAll("_"," ")} overlaps this rental window.`:"Available for the selected dates.";}

function applyVehicleDefaults(car){if(!car)return;builder.draft.vehicle_id=car.id;if(!Number(builder.draft.rate_amount||builder.quote?.rate_amount))builder.draft.rate_amount=car.price||0;if(!Number(builder.draft.security_deposit||builder.quote?.security_deposit))builder.draft.security_deposit=car.security_deposit||0;if(!builder.quote&&Number(car.delivery_base_fee||0)&&!builder.lineItems.some(i=>i.description==="Delivery"))builder.lineItems.push({id:uid(),description:"Delivery",quantity:1,rate:Number(car.delivery_base_fee),taxable:false});if(car.ownership_type==="partner"&&!Number(builder.draft.partner_cost||builder.quote?.partner_cost)){const p=partnerFor(car.id);builder.draft.partner_cost=Number(p?.partner_daily_cost||0)*duration();}}
function bindStepEvents(){const form=quoteForm();const sync=()=>{captureBuilderStep();updateBuilder();};form?.addEventListener("input",sync);form?.addEventListener("change",sync);form?.querySelector("[data-builder-lead]")?.addEventListener("change",e=>{const l=model.leads.find(x=>x.id===e.target.value);if(!l)return;const names=String(l.name||"").trim().split(/\s+/);form.elements.customer_first_name.value=names.shift()||"";form.elements.customer_last_name.value=names.join(" ");form.elements.customer_phone.value=l.phone||"";form.elements.customer_email.value=l.email||"";form.elements.lead_source.value=l.source||"Website lead";const car=model.cars.find(c=>String(c.name).toLowerCase()===String(l.vehicle).toLowerCase());applyVehicleDefaults(car);captureBuilderStep();updateBuilder();});form?.querySelector("[data-customer-search]")?.addEventListener("change",e=>{const c=model.customers.find(c=>`${fullName(c)} · ${c.phone||c.email}`===e.target.value);if(!c)return;form.elements.customer_id.value=c.id;form.elements.customer_first_name.value=c.first_name||"";form.elements.customer_last_name.value=c.last_name||"";form.elements.customer_phone.value=c.phone||"";form.elements.customer_email.value=c.email||"";form.elements.customer_company.value=c.company||"";form.elements.lead_source.value=c.lead_source||"";captureBuilderStep();updateBuilder();});form?.querySelector("[data-builder-vehicle]")?.addEventListener("change",()=>{captureBuilderStep();const car=model.cars.find(c=>c.id===value("vehicle_id"));applyVehicleDefaults(car);renderVehiclePreview();checkAvailability();updateBuilder();});form?.querySelector('[name="tax_enabled"]')?.addEventListener("change",e=>{form.elements.tax_rate.disabled=!e.target.checked;sync();});form?.querySelector("[data-expiration-choice]")?.addEventListener("change",e=>{if(e.target.value!=="custom"){const d=new Date();d.setHours(d.getHours()+Number(e.target.value));form.elements.expires_at.value=localInput(d);}sync();});form?.querySelector("[data-add-line]")?.addEventListener("click",()=>{builder.lineItems.push({id:uid(),description:"Delivery",quantity:1,rate:0,taxable:false});renderLineItems();updateBuilder();});form?.querySelector("[data-line-items]")?.addEventListener("input",lineItemEvent);form?.querySelector("[data-line-items]")?.addEventListener("change",lineItemEvent);form?.querySelector("[data-line-items]")?.addEventListener("click",lineItemEvent);form?.querySelector("[data-add-cost]")?.addEventListener("click",()=>{builder.costs.push({id:uid(),description:"Delivery cost",amount:0});renderCosts();updateBuilder();});form?.querySelector("[data-internal-costs]")?.addEventListener("input",costEvent);form?.querySelector("[data-internal-costs]")?.addEventListener("change",costEvent);form?.querySelector("[data-internal-costs]")?.addEventListener("click",costEvent);if(builder.step===3)setExpirationDefault();}
function lineItemEvent(e){const row=e.target.closest("[data-line-index]");if(!row)return;const i=Number(row.dataset.lineIndex);if(e.target.matches("[data-remove-line]")){builder.lineItems.splice(i,1);renderLineItems();updateBuilder();return;}const field=e.target.dataset.lineField;if(field)builder.lineItems[i][field]=field==="taxable"?e.target.checked:field==="quantity"||field==="rate"?Number(e.target.value||0):e.target.value;renderLineItems();updateBuilder();}
function costEvent(e){const row=e.target.closest("[data-cost-index]");if(!row)return;const i=Number(row.dataset.costIndex);if(e.target.matches("[data-remove-cost]")){builder.costs.splice(i,1);renderCosts();updateBuilder();return;}const field=e.target.dataset.costField;if(field)builder.costs[i][field]=field==="amount"?Number(e.target.value||0):e.target.value;renderCosts();updateBuilder();}
function setExpirationDefault(){const form=quoteForm(),input=form?.elements.expires_at;if(!form||!input||input.value)return;const d=new Date();d.setHours(d.getHours()+48);input.value=localInput(d);}

function payloadFromBuilder(){captureBuilderStep();const out={...(builder.quote||{}),...(builder.draft||{})};const t=clientTotals();out.customer_id=out.customer_id||null;out.lead_id=out.lead_id||null;out.vehicle_id=out.vehicle_id||null;out.assigned_user_id=out.assigned_user_id||null;out.start_at=toIso(out.start_at);out.end_at=toIso(out.end_at);out.rate_amount=Number(out.rate_amount||0);out.duration_value=t.d;out.line_items=builder.lineItems;out.rental_taxable=Boolean(out.rental_taxable);out.discount_value=Number(out.discount_value||0);out.tax_enabled=Boolean(out.tax_enabled);out.tax_rate=Number(out.tax_rate||0);out.amount_required_value=Number(out.amount_required_value||0);out.security_deposit=Number(out.security_deposit||0);out.partner_cost=Number(out.partner_cost||0);out.internal_costs=builder.costs;out.expires_at=toIso(out.expires_at);out.follow_up_at=followUpValue(out.follow_up_choice,out.follow_up_at);out.status=builder.quote?.status||"draft";for(const key of ["id","quote_number","access_token","public_url","created_at","updated_at","sent_at","viewed_at","accepted_at","deposit_paid_at","converted_at","invoice_id","reservation_id","stripe_checkout_session_id","stripe_payment_intent_id","stripe_payment_url","rental_subtotal","discount_amount","tax_amount","rental_total","amount_required","remaining_balance","total_internal_cost","expected_profit","customer_search","expiration_choice","follow_up_choice"])delete out[key];return out;}
function followUpValue(choice,custom){const d=new Date();if(choice==="later")d.setHours(d.getHours()+4);else if(choice==="tomorrow")d.setDate(d.getDate()+1);else if(choice==="two_days")d.setDate(d.getDate()+2);else if(choice==="custom")return toIso(custom);else return null;return d.toISOString();}
function validatePayload(p){if(!p.customer_first_name&&!p.customer_last_name)throw new Error("Enter or select the customer name.");if(!p.customer_phone&&!p.customer_email)throw new Error("Add the customer phone or email.");if(!p.vehicle_id)throw new Error("Select a fleet vehicle.");if(!p.start_at||!p.end_at||new Date(p.end_at)<=new Date(p.start_at))throw new Error("Choose a valid rental start and end.");if(document.querySelector("[data-quote-availability]")?.classList.contains("conflict"))throw new Error("Choose different dates or vehicle before saving this quote.");}
async function saveBuilder(send=false){const status=document.querySelector("[data-builder-status]");try{const payload=payloadFromBuilder();validatePayload(payload);status.textContent=send?"Saving and sending quote…":"Saving draft…";status.dataset.tone="";const result=builder.quote?.id?await api("quotes",{method:"PATCH",body:JSON.stringify({id:builder.quote.id,...payload})}):await api("quotes",{method:"POST",body:JSON.stringify(payload)});let saved=result.quote;if(send){const sent=await api("quotes",{method:"POST",body:JSON.stringify({action:"send",id:saved.id})});saved=sent.quote;toast(sent.delivery?.delivered?"Quote saved and emailed.":"Quote saved. Secure link is ready to send manually.");}else toast("Quote draft saved.");document.querySelector("[data-quote-builder-dialog]").close();await load(true);await openDetail(saved.id);}catch(error){status.textContent=error.message;status.dataset.tone="error";}}

function openBuilder(q=null){ensureDialogs();builder={quote:q,draft:{...(q||{})},step:0,lineItems:(q?.line_items||[]).map(i=>({...i,id:uid()})),costs:(q?.internal_costs||[]).map(i=>({...i,id:uid()}))};document.querySelector("[data-builder-title]").textContent=q?`Edit ${q.quote_number}`:"New Quote";document.querySelector("[data-builder-status]").textContent="";renderBuilderStep();document.querySelector("[data-quote-builder-dialog]").showModal();}

function bindDialogEvents(){const dialog=document.querySelector("[data-quote-builder-dialog]");dialog.querySelector("[data-close-builder]").addEventListener("click",()=>dialog.close());dialog.querySelector("[data-builder-back]").addEventListener("click",()=>{captureBuilderStep();builder.step=Math.max(builder.step-1,0);renderBuilderStep();});dialog.querySelector("[data-builder-next]").addEventListener("click",()=>{captureBuilderStep();builder.step=Math.min(builder.step+1,3);renderBuilderStep();});dialog.querySelector("[data-save-draft]").addEventListener("click",()=>saveBuilder(false));dialog.querySelector("[data-save-send]").addEventListener("click",()=>saveBuilder(true));dialog.querySelectorAll("[data-builder-step-button]").forEach(b=>b.addEventListener("click",()=>{captureBuilderStep();builder.step=Number(b.dataset.builderStepButton);renderBuilderStep();}));const decline=document.querySelector("[data-decline-dialog]");decline.querySelectorAll("[data-close-decline]").forEach(b=>b.addEventListener("click",()=>decline.close()));decline.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();await detailAction("decline",{lost_reason:new FormData(e.target).get("reason")});decline.close();});const payment=document.querySelector("[data-payment-dialog]");payment.querySelectorAll("[data-close-payment]").forEach(b=>b.addEventListener("click",()=>payment.close()));payment.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const d=new FormData(e.target);await detailAction("payment",{amount:Number(d.get("amount")),method:d.get("method"),reference:d.get("reference")});payment.close();});}

async function detailAction(action,extra={}){if(!selected)return;try{if(action==="edit")return openBuilder(selected);if(action==="copy"){await navigator.clipboard.writeText(selected.public_url);toast("Secure quote link copied.");return;}if(action==="delete"){if(!confirm(`Delete draft ${selected.quote_number}?`))return;await api(`quotes?id=${encodeURIComponent(selected.id)}`,{method:"DELETE"});toast("Draft quote deleted.");return load(true);}if(action==="duplicate"){const r=await api("quotes",{method:"POST",body:JSON.stringify({action:"duplicate",id:selected.id})});await load(true);toast("Quote duplicated.");return openDetail(r.quote.id);}if(action==="send"){const r=await api("quotes",{method:"POST",body:JSON.stringify({action:"send",id:selected.id})});toast(r.delivery?.delivered?"Quote emailed to the customer.":"Secure link is ready to send manually.");await load(true);return openDetail(selected.id);}if(action==="accept")await api("quotes",{method:"POST",body:JSON.stringify({action:"status",status:"accepted",id:selected.id})});else if(action==="decline")await api("quotes",{method:"POST",body:JSON.stringify({action:"status",status:"declined",id:selected.id,...extra})});else if(action==="cancel"){if(!confirm(`Cancel ${selected.quote_number}?`))return;await api("quotes",{method:"POST",body:JSON.stringify({action:"status",status:"cancelled",id:selected.id})});}else if(action==="payment")await api("quotes",{method:"POST",body:JSON.stringify({action:"record_payment",id:selected.id,...extra})});else if(action==="convert"){if(!confirm(`Convert ${selected.quote_number} to the existing invoice and reservation workflow?`))return;const result=await api("quotes",{method:"POST",body:JSON.stringify({action:"convert",id:selected.id})});toast(result.existing?"This quote was already converted.":`Reservation ${result.reservation.agreement_number} created.`);}await load(true);await openDetail(selected.id);}catch(error){toast(error.message,"error");}}

async function load(force=false){if(loaded&&!force){renderList();return;}root.innerHTML=`<div class="crm-loading-state quotes-loading">Loading quotes…</div>`;try{model=await api();loaded=true;renderList();}catch(error){root.innerHTML=`<div class="quote-v2-error"><strong>Quotes need attention</strong><p>${escapeHtml(error.message)}</p><button class="secondary-button" type="button" data-retry-quotes>Retry</button></div>`;}}

root?.addEventListener("input",e=>{if(e.target.matches("[data-quote-search]")){filter.search=e.target.value;renderList();}});
root?.addEventListener("change",e=>{if(e.target.matches("[data-quote-filter]")){filter[e.target.dataset.quoteFilter]=e.target.value;renderList();}if(e.target.matches("[data-followup-choice]")){root.querySelector("[data-followup-custom]").hidden=e.target.value!=="custom";}});
root?.addEventListener("click",async e=>{const scope=e.target.closest("[data-quote-scope]");if(scope){filter.scope=scope.dataset.quoteScope;renderList();return;}if(e.target.closest("[data-empty-new-quote]"))return openBuilder();if(e.target.closest("[data-retry-quotes]"))return load(true);if(e.target.closest("[data-back-quotes]"))return renderList();const open=e.target.closest("[data-open-quote-button]")||e.target.closest("[data-open-quote]");if(open)return openDetail(open.dataset.openQuoteButton||open.dataset.openQuote);const action=e.target.closest("[data-detail-action]");if(action){const name=action.dataset.detailAction;if(name==="decline")return document.querySelector("[data-decline-dialog]").showModal();if(name==="payment")return document.querySelector("[data-payment-dialog]").showModal();return detailAction(name);}if(e.target.closest("[data-save-followup]")){const choice=root.querySelector("[data-followup-choice]").value,custom=root.querySelector("[data-followup-custom]").value;try{await api("quotes",{method:"POST",body:JSON.stringify({action:"follow_up",id:selected.id,follow_up_at:followUpValue(choice,custom)})});toast("Follow-up scheduled.");await load(true);await openDetail(selected.id);}catch(error){toast(error.message,"error");}return;}const reservation=e.target.closest("[data-open-reservation]");if(reservation){document.querySelector('[data-crm-section="agreements"]')?.click();window.dispatchEvent(new CustomEvent("prestige:open-agreement",{detail:{id:reservation.dataset.openReservation}}));return;}const invoice=e.target.closest("[data-open-quote-invoice]");if(invoice){document.querySelector('[data-crm-section="invoices"]')?.click();window.dispatchEvent(new CustomEvent("prestige:open-invoice",{detail:{id:invoice.dataset.openQuoteInvoice}}));}});
root?.addEventListener("keydown",e=>{const row=e.target.closest("[data-open-quote]");if(row&&["Enter"," "].includes(e.key)){e.preventDefault();openDetail(row.dataset.openQuote);}});
newButton?.addEventListener("click",()=>{if(!loaded)return load(true).then(()=>openBuilder());openBuilder();});
window.addEventListener("prestige:new-quote-for-vehicle",async(event)=>{if(!loaded)await load(true);const vehicle=event.detail?.vehicle;openBuilder();if(vehicle){builder.draft.vehicle_id=vehicle.id;applyVehicleDefaults(model.cars.find(c=>c.id===vehicle.id)||vehicle);builder.step=1;renderBuilderStep();}});
navButton?.addEventListener("click",()=>load());
supabase.auth.onAuthStateChange((event,session)=>{if(!session){loaded=false;model={quotes:[],customers:[],leads:[],cars:[],partners:[],employees:[],reservations:[],blocks:[]};}else if(document.querySelector('[data-section-panel="requests"]')?.classList.contains("active"))load();});
ensureDialogs();
